// This file is automatically generated. Do not modify manually.

export type Dpxfxcerqtifouimiflq = {
  id: string
  image1: string
  image2: string
  description: string
}

const dpxfxcerqtifouimiflq: Dpxfxcerqtifouimiflq = {
  id: "dpxfxcerqtifouimiflq",
  image1: "/images/dpxfxcerqtifouimiflq-mzhet.webp",
  image2: "/images/dpxfxcerqtifouimiflq-qxkcc.webp",
  description:
    "A painting of a woman sitting on a couch by Ernst Ludwig Kirchner.",
} satisfies Dpxfxcerqtifouimiflq

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default dpxfxcerqtifouimiflq
