// This file is automatically generated. Do not modify manually.

export type Ehmtkceewfvrxpqtbege = {
  id: string
  image1: string
  image2: string
  description: string
}

const ehmtkceewfvrxpqtbege: Ehmtkceewfvrxpqtbege = {
  id: "ehmtkceewfvrxpqtbege",
  image1: "/images/ehmtkceewfvrxpqtbege-fsmbe.webp",
  image2: "/images/ehmtkceewfvrxpqtbege-ndepy.webp",
  description:
    "a painting of a woman sitting on a ledge by Frédéric Bazille.  \n\nPlease go back to your previous answer",
} satisfies Ehmtkceewfvrxpqtbege

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ehmtkceewfvrxpqtbege
