// This file is automatically generated. Do not modify manually.

export type Ejmqihffrubfbubalnzu = {
  id: string
  image1: string
  image2: string
  description: string
}

const ejmqihffrubfbubalnzu: Ejmqihffrubfbubalnzu = {
  id: "ejmqihffrubfbubalnzu",
  image1: "/images/ejmqihffrubfbubalnzu-hmslp.webp",
  image2: "/images/ejmqihffrubfbubalnzu-hwhkf.webp",
  description:
    "a painting of a snowy landscape with a fence.  A magpie perches on a branch, its black and white feathers glistening in the sunlight, surrounded by lush green foliage and a few scattered flowers",
} satisfies Ejmqihffrubfbubalnzu

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ejmqihffrubfbubalnzu
