// This file is automatically generated. Do not modify manually.

export type Fnclerpjdgekkpmmqdwj = {
  id: string
  image1: string
  image2: string
  description: string
}

const fnclerpjdgekkpmmqdwj: Fnclerpjdgekkpmmqdwj = {
  id: "fnclerpjdgekkpmmqdwj",
  image1: "/images/fnclerpjdgekkpmmqdwj-mvvmt.webp",
  image2: "/images/fnclerpjdgekkpmmqdwj-vujsh.webp",
  description: "a cool cat",
} satisfies Fnclerpjdgekkpmmqdwj

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default fnclerpjdgekkpmmqdwj
