// This file is automatically generated. Do not modify manually.

export type Hbykyvdrmygkmpkzpxfb = {
  id: string
  image1: string
  image2: string
  description: string
}

const hbykyvdrmygkmpkzpxfb: Hbykyvdrmygkmpkzpxfb = {
  id: "hbykyvdrmygkmpkzpxfb",
  image1: "/images/hbykyvdrmygkmpkzpxfb-eqmed.webp",
  image2: "/images/hbykyvdrmygkmpkzpxfb-lvnbp.webp",
  description:
    "a painting of a boat on a body of water by Blanche Hoschedé Monet.  A hazy, yellow-orange sun rises over a calm, dark sea, with a few ships and boats scattered across the horizon, while a misty atmosphere shrouds the surrounding cityscape",
} satisfies Hbykyvdrmygkmpkzpxfb

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default hbykyvdrmygkmpkzpxfb
