// This file is automatically generated. Do not modify manually.

export type Hskpaalclugibzepegpk = {
  id: string
  image1: string
  image2: string
  description: string
}

const hskpaalclugibzepegpk: Hskpaalclugibzepegpk = {
  id: "hskpaalclugibzepegpk",
  image1: "/images/hskpaalclugibzepegpk-pebve.webp",
  image2: "/images/hskpaalclugibzepegpk-uikyk.webp",
  description:
    "This impressionist painting by Pierre-Auguste Renoir depicts a scene at a park on a Sunday afternoon in Paris, France. It shows people enjoying themselves at the Ball at Le Moulin de la Galette. In the foreground, a group of men and women are dancing while wearing fashionable clothes such as dresses, hats, and neckties. Some of them are holding cups or carafes of drinks. There are also several people sitting at tables nearby, some with their backs turned towards us. Behind them, we can see more people walking around or sitting under trees. The colors used in this painting give it a warm and cheerful atmosphere which reflects the happy mood of the people depicted.",
} satisfies Hskpaalclugibzepegpk

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default hskpaalclugibzepegpk
