// This file is automatically generated. Do not modify manually.

export type Htnvhtbzbygsjdqwueko = {
  id: string
  image1: string
  image2: string
  description: string
}

const htnvhtbzbygsjdqwueko: Htnvhtbzbygsjdqwueko = {
  id: "htnvhtbzbygsjdqwueko",
  image1: "/images/htnvhtbzbygsjdqwueko-cmadf.webp",
  image2: "/images/htnvhtbzbygsjdqwueko-ufeof.webp",
  description:
    "a painting of people walking in the snow by Blanche Hoschedé Monet.  \n\nA group of people, including children, are gathered around a frozen pond, surrounded by snow-covered trees and buildings, with a distant view of the Seine River",
} satisfies Htnvhtbzbygsjdqwueko

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default htnvhtbzbygsjdqwueko
