// This file is automatically generated. Do not modify manually.

export type Iwvtwlpxvidyyugtjxsv = {
  id: string
  image1: string
  image2: string
  description: string
}

const iwvtwlpxvidyyugtjxsv: Iwvtwlpxvidyyugtjxsv = {
  id: "iwvtwlpxvidyyugtjxsv",
  image1: "/images/iwvtwlpxvidyyugtjxsv-jvjuw.webp",
  image2: "/images/iwvtwlpxvidyyugtjxsv-wbrkh.webp",
  description:
    "a painting of a cathedral with a blue sky in the background by Blanche Hoschedé Monet.  \n\nHere is your one sentence description: \nThe painting depicts a detailed and realistic scene of Rouen Cathedral's portal and tower, with intricate stone carvings and architectural details, bathed in warm sunlight and shadow",
} satisfies Iwvtwlpxvidyyugtjxsv

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default iwvtwlpxvidyyugtjxsv
