// This file is automatically generated. Do not modify manually.

export type Jrrhjvdqophqebbrfqwe = {
  id: string
  image1: string
  image2: string
  description: string
}

const jrrhjvdqophqebbrfqwe: Jrrhjvdqophqebbrfqwe = {
  id: "jrrhjvdqophqebbrfqwe",
  image1: "/images/jrrhjvdqophqebbrfqwe-abedh.webp",
  image2: "/images/jrrhjvdqophqebbrfqwe-fqgbd.webp",
  description:
    "a painting of a woman wearing a yellow scarf.  \n\nA young woman with a bright smile is shown standing in a field, surrounded by lush green vegetation and colorful flowers, holding a basket and wearing a traditional folk costume",
} satisfies Jrrhjvdqophqebbrfqwe

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default jrrhjvdqophqebbrfqwe
