// This file is automatically generated. Do not modify manually.

export type Jxfveyhnjoetxtbjzsot = {
  id: string
  image1: string
  image2: string
  description: string
}

const jxfveyhnjoetxtbjzsot: Jxfveyhnjoetxtbjzsot = {
  id: "jxfveyhnjoetxtbjzsot",
  image1: "/images/jxfveyhnjoetxtbjzsot-agxld.webp",
  image2: "/images/jxfveyhnjoetxtbjzsot-wnvtu.webp",
  description:
    "A portrait of a man playing a guitar. The man has a long, curly beard and wears a military uniform. He is standing and playing his guitar while looking out at the viewer. The painting is very detailed and realistic.",
} satisfies Jxfveyhnjoetxtbjzsot

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default jxfveyhnjoetxtbjzsot
