// This file is automatically generated. Do not modify manually.

export type Kiqgnnavfxulbcgxffrk = {
  id: string
  image1: string
  image2: string
  description: string
}

const kiqgnnavfxulbcgxffrk: Kiqgnnavfxulbcgxffrk = {
  id: "kiqgnnavfxulbcgxffrk",
  image1: "/images/kiqgnnavfxulbcgxffrk-heuoi.webp",
  image2: "/images/kiqgnnavfxulbcgxffrk-tmdfu.webp",
  description:
    "a painting of a building with a clock tower by Eugène Boudin.  \n\nA small village church stands in the center of a quiet, moonlit evening scene, surrounded by tall trees and a few scattered buildings, with a misty, dreamy quality to the atmosphere",
} satisfies Kiqgnnavfxulbcgxffrk

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default kiqgnnavfxulbcgxffrk
