// This file is automatically generated. Do not modify manually.

export type Lhdpenchnzkbsiwqcpae = {
  id: string
  image1: string
  image2: string
  description: string
}

const lhdpenchnzkbsiwqcpae: Lhdpenchnzkbsiwqcpae = {
  id: "lhdpenchnzkbsiwqcpae",
  image1: "/images/lhdpenchnzkbsiwqcpae-ygqtk.webp",
  image2: "/images/lhdpenchnzkbsiwqcpae-ylitk.webp",
  description:
    "The painting shows a detailed painting of two men riding a bike, painted in the style of Esao Andrews. The painting won a behance contest and is a folk art painting that features a matte drawing. It is an official art piece.",
} satisfies Lhdpenchnzkbsiwqcpae

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default lhdpenchnzkbsiwqcpae
