// This file is automatically generated. Do not modify manually.

export type Nqfjjxlpczbifuuldnkg = {
  id: string
  image1: string
  image2: string
  description: string
}

const nqfjjxlpczbifuuldnkg: Nqfjjxlpczbifuuldnkg = {
  id: "nqfjjxlpczbifuuldnkg",
  image1: "/images/nqfjjxlpczbifuuldnkg-erdfz.webp",
  image2: "/images/nqfjjxlpczbifuuldnkg-veeze.webp",
  description:
    "a painting of people walking down a street by Frédéric Bazille.  A group of people are gathered around a table in a park, with a large tree and a path in the background",
} satisfies Nqfjjxlpczbifuuldnkg

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default nqfjjxlpczbifuuldnkg
