// This file is automatically generated. Do not modify manually.

export type Nvbuscdmnljcaubxfgqz = {
  id: string
  image1: string
  image2: string
  description: string
}

const nvbuscdmnljcaubxfgqz: Nvbuscdmnljcaubxfgqz = {
  id: "nvbuscdmnljcaubxfgqz",
  image1: "/images/nvbuscdmnljcaubxfgqz-noqbi.webp",
  image2: "/images/nvbuscdmnljcaubxfgqz-wmiqu.webp",
  description:
    "a painting of a wheat field with crows flying over it by Vincent Van Gogh.  \n\nHere is the description:\n\nA desolate, barren wheatfield stretches across the canvas, with dark crows scattered throughout, some flying overhead while others perch on the dry, golden stalks",
} satisfies Nvbuscdmnljcaubxfgqz

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default nvbuscdmnljcaubxfgqz
