// This file is automatically generated. Do not modify manually.

export type Nymtruukpifxmcbfuakg = {
  id: string
  image1: string
  image2: string
  description: string
}

const nymtruukpifxmcbfuakg: Nymtruukpifxmcbfuakg = {
  id: "nymtruukpifxmcbfuakg",
  image1: "/images/nymtruukpifxmcbfuakg-dggcd.webp",
  image2: "/images/nymtruukpifxmcbfuakg-tbpyo.webp",
  description:
    "a painting of a woman sitting on a bench.  \n\nPlease answer: \nA peasant sits in a rustic setting, reading a book with a pipe in his hand and a gentle smile on his face",
} satisfies Nymtruukpifxmcbfuakg

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default nymtruukpifxmcbfuakg
