// This file is automatically generated. Do not modify manually.

export type Qrwhosbsrrhnwkqrwwwo = {
  id: string
  image1: string
  image2: string
  description: string
}

const qrwhosbsrrhnwkqrwwwo: Qrwhosbsrrhnwkqrwwwo = {
  id: "qrwhosbsrrhnwkqrwwwo",
  image1: "/images/qrwhosbsrrhnwkqrwwwo-moaeh.webp",
  image2: "/images/qrwhosbsrrhnwkqrwwwo-ujljk.webp",
  description:
    "The painting shows a group of women sitting in a garden with trees, flowers, and dresses. It is a landscape painting with vibrant colors and was painted in the impressionist style.",
} satisfies Qrwhosbsrrhnwkqrwwwo

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default qrwhosbsrrhnwkqrwwwo
