// This file is automatically generated. Do not modify manually.

export type Tloosgusbelpbtawlbjq = {
  id: string
  image1: string
  image2: string
  description: string
}

const tloosgusbelpbtawlbjq: Tloosgusbelpbtawlbjq = {
  id: "tloosgusbelpbtawlbjq",
  image1: "/images/tloosgusbelpbtawlbjq-pkfqm.webp",
  image2: "/images/tloosgusbelpbtawlbjq-rqjlt.webp",
  description:
    "a painting of a woman sitting on a couch by Antonio Mancini.  \n\nA young woman with a pale complexion and dark hair is depicted in a formal portrait, wearing a high-necked dress with a white collar and a brooch at the throat, against a backdrop of a soft, muted blue",
} satisfies Tloosgusbelpbtawlbjq

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default tloosgusbelpbtawlbjq
