// This file is automatically generated. Do not modify manually.

export type Uhphchxcvsvcxuecedww = {
  id: string
  image1: string
  image2: string
  description: string
}

const uhphchxcvsvcxuecedww: Uhphchxcvsvcxuecedww = {
  id: "uhphchxcvsvcxuecedww",
  image1: "/images/uhphchxcvsvcxuecedww-vkflw.webp",
  image2: "/images/uhphchxcvsvcxuecedww-xxmfr.webp",
  description:
    "a painting of a table with a tea set on it by Blanche Hoschedé Monet.  \n\nHere is your answer:\n\nA woman sits alone at a table in a garden, eating a slice of peach pie and drinking a glass of wine, surrounded by lush greenery and a warm, sunny atmosphere",
} satisfies Uhphchxcvsvcxuecedww

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default uhphchxcvsvcxuecedww
