// This file is automatically generated. Do not modify manually.

export type Vgisvznieanozdqrkueq = {
  id: string
  image1: string
  image2: string
  description: string
}

const vgisvznieanozdqrkueq: Vgisvznieanozdqrkueq = {
  id: "vgisvznieanozdqrkueq",
  image1: "/images/vgisvznieanozdqrkueq-pzodq.webp",
  image2: "/images/vgisvznieanozdqrkueq-xqwfe.webp",
  description:
    "a painting of a woman wearing a hat.  \n\nThe woman in the portrait is depicted sitting in a chair, wearing a yellow dress with a white apron, her hands clasped together in her lap, and her face turned slightly towards the viewer with a gentle, enigmatic smile",
} satisfies Vgisvznieanozdqrkueq

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default vgisvznieanozdqrkueq
