// This file is automatically generated. Do not modify manually.

export type Wjovunxrmxwttuoxrdub = {
  id: string
  image1: string
  image2: string
  description: string
}

const wjovunxrmxwttuoxrdub: Wjovunxrmxwttuoxrdub = {
  id: "wjovunxrmxwttuoxrdub",
  image1: "/images/wjovunxrmxwttuoxrdub-lhgof.webp",
  image2: "/images/wjovunxrmxwttuoxrdub-plkhs.webp",
  description:
    "a painting of a woman looking in a mirror by Édouard Vuillard.  Here it is:\n\nIn this painting, a serene and intimate interior scene is depicted, with a woman sitting at a table surrounded by lush greenery and wearing a red ribbon in her hair, while a vase of flowers and a Japanese screen add to the tranquil atmosphere",
} satisfies Wjovunxrmxwttuoxrdub

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default wjovunxrmxwttuoxrdub
