// This file is automatically generated. Do not modify manually.

export type Xnwnafnpaleegeiuqtcl = {
  id: string
  image1: string
  image2: string
  description: string
}

const xnwnafnpaleegeiuqtcl: Xnwnafnpaleegeiuqtcl = {
  id: "xnwnafnpaleegeiuqtcl",
  image1: "/images/xnwnafnpaleegeiuqtcl-cgjpv.webp",
  image2: "/images/xnwnafnpaleegeiuqtcl-lgnvc.webp",
  description:
    "Franz Marc's Red and Blue Horses is a painting that uses color and geometric shapes to create an abstract representation of two horses in motion. The painting is a masterpiece of Expressionism, a style of art that emphasizes emotions and subjective experience. Marc's use of color and shape creates a dynamic and energetic composition that captures the movement and power of the horses.",
} satisfies Xnwnafnpaleegeiuqtcl

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default xnwnafnpaleegeiuqtcl
