// This file is automatically generated. Do not modify manually.

export type Xtjqqhjsusmwtpodhplk = {
  id: string
  image1: string
  image2: string
  description: string
}

const xtjqqhjsusmwtpodhplk: Xtjqqhjsusmwtpodhplk = {
  id: "xtjqqhjsusmwtpodhplk",
  image1: "/images/xtjqqhjsusmwtpodhplk-hipro.webp",
  image2: "/images/xtjqqhjsusmwtpodhplk-xzkhs.webp",
  description:
    "a painting of two women in a field.  A dark blue sky with a crescent moon is seen above two girls standing together, looking out at the viewer with their faces illuminated by a bright full moon hanging low in the sky",
} satisfies Xtjqqhjsusmwtpodhplk

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default xtjqqhjsusmwtpodhplk
