// This file is automatically generated. Do not modify manually.

export type Xyhfljgurauxjimwetko = {
  id: string
  image1: string
  image2: string
  description: string
}

const xyhfljgurauxjimwetko: Xyhfljgurauxjimwetko = {
  id: "xyhfljgurauxjimwetko",
  image1: "/images/xyhfljgurauxjimwetko-igdhy.webp",
  image2: "/images/xyhfljgurauxjimwetko-mrcfn.webp",
  description:
    "a painting of a city street with buildings by Santiago Rusiñol.  A busy street scene with people of all ages and occupations going about their daily lives, with horse-drawn carriages, street vendors, and tall buildings in the background",
} satisfies Xyhfljgurauxjimwetko

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default xyhfljgurauxjimwetko
