// This file is automatically generated. Do not modify manually.

export type Ynksbpvkvjbrxslqklhi = {
  id: string
  image1: string
  image2: string
  description: string
}

const ynksbpvkvjbrxslqklhi: Ynksbpvkvjbrxslqklhi = {
  id: "ynksbpvkvjbrxslqklhi",
  image1: "/images/ynksbpvkvjbrxslqklhi-kefyb.webp",
  image2: "/images/ynksbpvkvjbrxslqklhi-qrqxu.webp",
  description:
    "a painting of a large building with a clock tower.  A large, imposing cathedral with a stone façade, its portal flanked by two statues of saints, stands bathed in warm morning light, with the sky above a deep shade of blue and the surrounding buildings reduced to tiny silhouettes",
} satisfies Ynksbpvkvjbrxslqklhi

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ynksbpvkvjbrxslqklhi
