// This file is automatically generated. Do not modify manually.

export type Impressionism = {
  id: string
  name: string
  questions: string[]
}

const impressionism: Impressionism = {
  id: "impressionism",
  name: "Impressionism",
  questions: [
    "iwvtwlpxvidyyugtjxsv",
    "nqfjjxlpczbifuuldnkg",
    "nymtruukpifxmcbfuakg",
    "kiqgnnavfxulbcgxffrk",
    "nvbuscdmnljcaubxfgqz",
    "hbykyvdrmygkmpkzpxfb",
    "lhlnnbmpptynwwkgulvy",
    "nflovvpmqsxdmkxiutrc",
    "wjovunxrmxwttuoxrdub",
    "htnvhtbzbygsjdqwueko",
    "tloosgusbelpbtawlbjq",
    "rzdptvkkqmltptcqlycy",
    "ehmtkceewfvrxpqtbege",
    "sskzgjiwtpxbmslekplh",
    "ynksbpvkvjbrxslqklhi",
    "ejmqihffrubfbubalnzu",
    "vgisvznieanozdqrkueq",
    "jrrhjvdqophqebbrfqwe",
  ],
} satisfies Impressionism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default impressionism
