// This file is automatically generated. Do not modify manually.

export type Movements = string[]

const movements: Movements = ["impressionism"] satisfies Movements

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default movements
