// This file is automatically generated. Do not modify manually.

export type Bcxfdafmapxgmwyfkqik = {
  id: string
  image1: string
  image2: string
  description: string
}

const bcxfdafmapxgmwyfkqik: Bcxfdafmapxgmwyfkqik = {
  id: "bcxfdafmapxgmwyfkqik",
  image1: "/images/bcxfdafmapxgmwyfkqik-jrqck.webp",
  image2: "/images/bcxfdafmapxgmwyfkqik-sqfsj.webp",
  description:
    "The painting depicts the rocks of Belle-Île-en-Mer, an island off the coast of Brittany in France. The rocks are bathed in the light of the setting sun, and the sea is calm and blue. The rocks are covered in a thin layer of white foam, and the waves are gentle and rolling. The sky is clear and blue, and the clouds are thin and wispy. The painting is a beautiful example of the Impressionist style, with its use of light and color to create a sense of atmosphere and emotion.",
} satisfies Bcxfdafmapxgmwyfkqik

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default bcxfdafmapxgmwyfkqik
