// This file is automatically generated. Do not modify manually.

export type Bjkhrbnkelpmfjsxkocd = {
  id: string
  image1: string
  image2: string
  description: string
}

const bjkhrbnkelpmfjsxkocd: Bjkhrbnkelpmfjsxkocd = {
  id: "bjkhrbnkelpmfjsxkocd",
  image1: "/images/bjkhrbnkelpmfjsxkocd-hfndw.webp",
  image2: "/images/bjkhrbnkelpmfjsxkocd-ouipv.webp",
  description:
    "This painting by Alexandre de Riquer is titled Ducks and was painted in 1890. It is part of the Art Nouveau movement and is done in oil paint on canvas. The painting features ducks flying in the sky.",
} satisfies Bjkhrbnkelpmfjsxkocd

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default bjkhrbnkelpmfjsxkocd
