// This file is automatically generated. Do not modify manually.

export type Cthnjoacjdpwgcsotcsf = {
  id: string
  image1: string
  image2: string
  description: string
}

const cthnjoacjdpwgcsotcsf: Cthnjoacjdpwgcsotcsf = {
  id: "cthnjoacjdpwgcsotcsf",
  image1: "/images/cthnjoacjdpwgcsotcsf-rjixt.webp",
  image2: "/images/cthnjoacjdpwgcsotcsf-sbvfc.webp",
  description:
    "a painting of a crowd of people in a park.  \n\nA group of young people, including a couple dancing in the foreground, gather in a festive atmosphere surrounded by a lush garden, a wooden fence, and a distant view of a Parisian landscape",
} satisfies Cthnjoacjdpwgcsotcsf

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default cthnjoacjdpwgcsotcsf
