// This file is automatically generated. Do not modify manually.

export type Gyecqwxmoqncqtduykqh = {
  id: string
  image1: string
  image2: string
  description: string
}

const gyecqwxmoqncqtduykqh: Gyecqwxmoqncqtduykqh = {
  id: "gyecqwxmoqncqtduykqh",
  image1: "/images/gyecqwxmoqncqtduykqh-jvoio.webp",
  image2: "/images/gyecqwxmoqncqtduykqh-yumvj.webp",
  description:
    "This is a painting of a young girl. She is wearing a pink dress and a white apron. She is standing in front of a window. The window has a green curtain. There is a table next to her. On the table there is a vase with flowers. The girl is looking at the viewer.",
} satisfies Gyecqwxmoqncqtduykqh

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default gyecqwxmoqncqtduykqh
