// This file is automatically generated. Do not modify manually.

export type Gysfplmeoocshznbyyil = {
  id: string
  image1: string
  image2: string
  description: string
}

const gysfplmeoocshznbyyil: Gysfplmeoocshznbyyil = {
  id: "gysfplmeoocshznbyyil",
  image1: "/images/gysfplmeoocshznbyyil-nwimp.webp",
  image2: "/images/gysfplmeoocshznbyyil-qjnxc.webp",
  description:
    "This portrait of Prince Ferdinand Philippe, Duke of Orléans was painted by Jean Auguste Dominique Ingres in 1832. The prince is depicted standing with his hand resting on the hilt of his sword, looking directly at the viewer. He is wearing a military uniform and has a red sash across his chest. The background is dark and brooding, which contrasts with the bright colors of the prince's uniform. The painting is a powerful representation of the French monarchy and its military might.",
} satisfies Gysfplmeoocshznbyyil

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default gysfplmeoocshznbyyil
