// This file is automatically generated. Do not modify manually.

export type Hurrwovmmmelsglggdpc = {
  id: string
  image1: string
  image2: string
  description: string
}

const hurrwovmmmelsglggdpc: Hurrwovmmmelsglggdpc = {
  id: "hurrwovmmmelsglggdpc",
  image1: "/images/hurrwovmmmelsglggdpc-bsdir.webp",
  image2: "/images/hurrwovmmmelsglggdpc-tqpoi.webp",
  description:
    "a painting of two people sitting on a beach.  \n\nA group of people, including children and adults, are shown enjoying a sunny day at the beach, with some playing in the water, others lounging under colorful umbrellas, and a few sitting on the sand building sandcastles",
} satisfies Hurrwovmmmelsglggdpc

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default hurrwovmmmelsglggdpc
