// This file is automatically generated. Do not modify manually.

export type Ibpqkyxvjurdxnklddsw = {
  id: string
  image1: string
  image2: string
  description: string
}

const ibpqkyxvjurdxnklddsw: Ibpqkyxvjurdxnklddsw = {
  id: "ibpqkyxvjurdxnklddsw",
  image1: "/images/ibpqkyxvjurdxnklddsw-lntgl.webp",
  image2: "/images/ibpqkyxvjurdxnklddsw-ymvcv.webp",
  description:
    "This painting is by Pierre-Auguste Renoir and it depicts a sailboat on the shore of the Seine.",
} satisfies Ibpqkyxvjurdxnklddsw

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ibpqkyxvjurdxnklddsw
