// This file is automatically generated. Do not modify manually.

export type Ighlvldkmwxgtnmnnvxd = {
  id: string
  image1: string
  image2: string
  description: string
}

const ighlvldkmwxgtnmnnvxd: Ighlvldkmwxgtnmnnvxd = {
  id: "ighlvldkmwxgtnmnnvxd",
  image1: "/images/ighlvldkmwxgtnmnnvxd-esvsf.webp",
  image2: "/images/ighlvldkmwxgtnmnnvxd-wkwvj.webp",
  description:
    "This is a painting of a nude woman standing in front of a mirror, she is in the process of doing her hair. She has brown hair that is done up in a chignon. There is an earring visible on her right earlobe. Her back and intergluteal cleft are clearly visible. She has very pale skin which contrasts nicely with the dark background. The painting is painted in the neoclassical style and is made with oil paint on canvas.",
} satisfies Ighlvldkmwxgtnmnnvxd

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ighlvldkmwxgtnmnnvxd
