// This file is automatically generated. Do not modify manually.

export type Iyfxsdzuinpgqpbrybdu = {
  id: string
  image1: string
  image2: string
  description: string
}

const iyfxsdzuinpgqpbrybdu: Iyfxsdzuinpgqpbrybdu = {
  id: "iyfxsdzuinpgqpbrybdu",
  image1: "/images/iyfxsdzuinpgqpbrybdu-ibrzi.webp",
  image2: "/images/iyfxsdzuinpgqpbrybdu-iykbx.webp",
  description:
    "This painting depicts a beautiful landscape with horses grazing on green grass, farmers working in fields and streams flowing through rolling hills covered in trees. It has been painted using oil paints on canvas which gives it an interesting texture that brings out the colors even more vividly than they appear in reality.",
} satisfies Iyfxsdzuinpgqpbrybdu

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default iyfxsdzuinpgqpbrybdu
