// This file is automatically generated. Do not modify manually.

export type Jlmplrldbhibfqwdyrog = {
  id: string
  image1: string
  image2: string
  description: string
}

const jlmplrldbhibfqwdyrog: Jlmplrldbhibfqwdyrog = {
  id: "jlmplrldbhibfqwdyrog",
  image1: "/images/jlmplrldbhibfqwdyrog-qkcil.webp",
  image2: "/images/jlmplrldbhibfqwdyrog-vrvqi.webp",
  description:
    'The painting shows Richard Gallo sitting in an armchair, reading a newspaper called "Le Figaro".',
} satisfies Jlmplrldbhibfqwdyrog

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default jlmplrldbhibfqwdyrog
