// This file is automatically generated. Do not modify manually.

export type Ldcsdylorsoygeqlcwhe = {
  id: string
  image1: string
  image2: string
  description: string
}

const ldcsdylorsoygeqlcwhe: Ldcsdylorsoygeqlcwhe = {
  id: "ldcsdylorsoygeqlcwhe",
  image1: "/images/ldcsdylorsoygeqlcwhe-jkiqj.webp",
  image2: "/images/ldcsdylorsoygeqlcwhe-visup.webp",
  description:
    "The painting depicts a woman wearing a hat. She is naked except for her dress and toplessness. Her breasts are visible. She has a areola and her nipples are visible. She has a hat on her head.",
} satisfies Ldcsdylorsoygeqlcwhe

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ldcsdylorsoygeqlcwhe
