// This file is automatically generated. Do not modify manually.

export type Nbdxefptldxepbgblsqw = {
  id: string
  image1: string
  image2: string
  description: string
}

const nbdxefptldxepbgblsqw: Nbdxefptldxepbgblsqw = {
  id: "nbdxefptldxepbgblsqw",
  image1: "/images/nbdxefptldxepbgblsqw-ibwie.webp",
  image2: "/images/nbdxefptldxepbgblsqw-jltyi.webp",
  description:
    "The painting is called \"Nightscape with Two Girls\" and it's a genre art painting from the year 1900 that was painted in Spain. The material used to create the artwork was oil paint on canvas and it is in the style of Art Nouveau. The dimensions of the piece are 63 cm x 80 cm and it features two girls standing in front of a large tree with a full moon shining behind them. The girls appear to be wearing dresses, although they may not be visible due to the darkness of the night. The overall tone of the painting is dark and moody, with the focus being on the two girls and the tree. It has been suggested that this painting could represent a sense of longing or nostalgia for simpler times. Overall, this painting captures a peaceful moment between two young women who appear to be enjoying each other's company in the stillness of the night.",
} satisfies Nbdxefptldxepbgblsqw

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default nbdxefptldxepbgblsqw
