// This file is automatically generated. Do not modify manually.

export type Nupfqnmyicweeqraaiys = {
  id: string
  image1: string
  image2: string
  description: string
}

const nupfqnmyicweeqraaiys: Nupfqnmyicweeqraaiys = {
  id: "nupfqnmyicweeqraaiys",
  image1: "/images/nupfqnmyicweeqraaiys-gqxpm.webp",
  image2: "/images/nupfqnmyicweeqraaiys-rpcug.webp",
  description:
    "A young woman dressed in white and green holds her right hand over her chest. She has long hair that is braided and gathered on top of her head. Her lips are slightly parted and she looks off into the distance.",
} satisfies Nupfqnmyicweeqraaiys

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default nupfqnmyicweeqraaiys
