// This file is automatically generated. Do not modify manually.

export type Pwmpmbplwwytnhilwwdr = {
  id: string
  image1: string
  image2: string
  description: string
}

const pwmpmbplwwytnhilwwdr: Pwmpmbplwwytnhilwwdr = {
  id: "pwmpmbplwwytnhilwwdr",
  image1: "/images/pwmpmbplwwytnhilwwdr-jdgxe.webp",
  image2: "/images/pwmpmbplwwytnhilwwdr-lpmvl.webp",
  description:
    "A woman is depicted kneeling and crying on a ledge, her body showing dimples of Venus and glabrousness. She is mourning and sad, her long hair falling over her shoulders and down her back. Her nude body is exposed, showing her breasts and buttocks. She is alone in her sorrow.",
} satisfies Pwmpmbplwwytnhilwwdr

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default pwmpmbplwwytnhilwwdr
