// This file is automatically generated. Do not modify manually.

export type Qlsvccsgbcgutocvebff = {
  id: string
  image1: string
  image2: string
  description: string
}

const qlsvccsgbcgutocvebff: Qlsvccsgbcgutocvebff = {
  id: "qlsvccsgbcgutocvebff",
  image1: "/images/qlsvccsgbcgutocvebff-feplc.webp",
  image2: "/images/qlsvccsgbcgutocvebff-mbxwo.webp",
  description:
    "a painting of a man driving a car with a dog on the back.  \n\nA young man, Pere Romeu, sits in the back seat of an open-top car, while a friend, Ramon Casas, stands beside the vehicle, leaning against the door and looking at him with a smile",
} satisfies Qlsvccsgbcgutocvebff

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default qlsvccsgbcgutocvebff
