// This file is automatically generated. Do not modify manually.

export type Qoglsxjhxrvfvvszbjoe = {
  id: string
  image1: string
  image2: string
  description: string
}

const qoglsxjhxrvfvvszbjoe: Qoglsxjhxrvfvvszbjoe = {
  id: "qoglsxjhxrvfvvszbjoe",
  image1: "/images/qoglsxjhxrvfvvszbjoe-cdcxb.webp",
  image2: "/images/qoglsxjhxrvfvvszbjoe-lvsjm.webp",
  description:
    "A full moon shining over a still body of water with reflections from the moonlit sky shimmering in the rippling waves. A small rowboat is tied to a dock jutting out into the water with its oars lying across it. In the distance is a dark mass of land with pine trees silhouetted against the starry sky. The landscape is illuminated by the glow of the moon which casts shadows on the water and onto the shore where there is a small wooden house. There are no people in sight except for a single figure standing on the beach looking out at the moonlit scene.",
} satisfies Qoglsxjhxrvfvvszbjoe

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default qoglsxjhxrvfvvszbjoe
