// This file is automatically generated. Do not modify manually.

export type Rcywcqladkegcycgvdvk = {
  id: string
  image1: string
  image2: string
  description: string
}

const rcywcqladkegcycgvdvk: Rcywcqladkegcycgvdvk = {
  id: "rcywcqladkegcycgvdvk",
  image1: "/images/rcywcqladkegcycgvdvk-gdgpw.webp",
  image2: "/images/rcywcqladkegcycgvdvk-jbiwp.webp",
  description:
    "The painting Mars Being Disarmed by Venus is by Jacques-Louis David. It depicts the Roman god Mars being disarmed by the goddess Venus. Mars is shown as a clothed male figure, while Venus is shown as a naked female figure. The two figures are seated on a bench, with Mars sitting on the right side and Venus on the left. The painting is set in a classical setting, with a column and a statue in the background. The painting is an example of neoclassical art, which was popular in the late 18th and early 19th centuries.",
} satisfies Rcywcqladkegcycgvdvk

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default rcywcqladkegcycgvdvk
