// This file is automatically generated. Do not modify manually.

export type Rusvbdxmhriguybbaupq = {
  id: string
  image1: string
  image2: string
  description: string
}

const rusvbdxmhriguybbaupq: Rusvbdxmhriguybbaupq = {
  id: "rusvbdxmhriguybbaupq",
  image1: "/images/rusvbdxmhriguybbaupq-jylys.webp",
  image2: "/images/rusvbdxmhriguybbaupq-qgytp.webp",
  description:
    "A work from the Expressionist movement, this painting was completed by Austrian artist Egon Schiele in 1912. It is an oil painting on wood panel measuring 32.7 x 39.8 cm. The artwork depicts a portrait of a woman named Wally Neuzil, who was known as one of Schiele’s muses during his career. This piece belongs to the genre of portraiture, and features bold brushstrokes and vibrant colors characteristic of Expressionism.",
} satisfies Rusvbdxmhriguybbaupq

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default rusvbdxmhriguybbaupq
