// This file is automatically generated. Do not modify manually.

export type Sxivoiolobmjsasdohqm = {
  id: string
  image1: string
  image2: string
  description: string
}

const sxivoiolobmjsasdohqm: Sxivoiolobmjsasdohqm = {
  id: "sxivoiolobmjsasdohqm",
  image1: "/images/sxivoiolobmjsasdohqm-gnvut.webp",
  image2: "/images/sxivoiolobmjsasdohqm-mgxfh.webp",
  description:
    "This painting depicts a woman in a yellow dress. She is sitting on a chair and looking directly at the viewer. The background is dark and there is a window behind her. The woman has long brown hair and she is wearing a white blouse and a yellow skirt. She is holding a book in her lap and her hands are clasped together. The painting is called La Sargantaine (Portrait of Júlia Peraire) and it was created by Ramon Casas i Carbó in 1899.",
} satisfies Sxivoiolobmjsasdohqm

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default sxivoiolobmjsasdohqm
