// This file is automatically generated. Do not modify manually.

export type Teljehrhnxfrmridwthn = {
  id: string
  image1: string
  image2: string
  description: string
}

const teljehrhnxfrmridwthn: Teljehrhnxfrmridwthn = {
  id: "teljehrhnxfrmridwthn",
  image1: "/images/teljehrhnxfrmridwthn-ljrfx.webp",
  image2: "/images/teljehrhnxfrmridwthn-vmnmj.webp",
  description:
    "A still life of flowers, including scabiosa and ranunculus, is painted in an impressionist style. The background is a neutral color that blends into the surroundings.",
} satisfies Teljehrhnxfrmridwthn

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default teljehrhnxfrmridwthn
