// This file is automatically generated. Do not modify manually.

export type Vdchzmbekpibpjxaaoix = {
  id: string
  image1: string
  image2: string
  description: string
}

const vdchzmbekpibpjxaaoix: Vdchzmbekpibpjxaaoix = {
  id: "vdchzmbekpibpjxaaoix",
  image1: "/images/vdchzmbekpibpjxaaoix-iolsh.webp",
  image2: "/images/vdchzmbekpibpjxaaoix-vvrdb.webp",
  description:
    "In this painting, we see Count Stanislas Potocki, the famous Polish aristocrat, depicted in an equestrian pose on his horse. He is dressed in traditional Polish garb, including a wide-brimmed hat and flowing cloak. The background is a sweeping landscape, with rolling hills and trees. The painting is in the Neoclassical style, which emphasizes order and simplicity. This can be seen in the clean lines and balanced composition of the painting. The use of light and shadow is also typical of the Neoclassical style, creating a sense of depth and dimensionality. Overall, this painting is a beautiful example of the Neoclassical style and a tribute to the legacy of Count Stanislas Potocki.",
} satisfies Vdchzmbekpibpjxaaoix

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default vdchzmbekpibpjxaaoix
