// This file is automatically generated. Do not modify manually.

export type Vlrnabswgihxvvpbllpi = {
  id: string
  image1: string
  image2: string
  description: string
}

const vlrnabswgihxvvpbllpi: Vlrnabswgihxvvpbllpi = {
  id: "vlrnabswgihxvvpbllpi",
  image1: "/images/vlrnabswgihxvvpbllpi-unqiq.webp",
  image2: "/images/vlrnabswgihxvvpbllpi-zuope.webp",
  description:
    "In this neoclassical oil painting from 1784, Jacques-Louis David depicts the three Horatii brothers offering their lives and swords to their father as they prepare to confront the three Curatti brothers in order to settle the dispute between Rome and Alba. It is a large painting measuring 330 cm high and 425 cm wide. The composition is structured around a series of diagonal lines that converge at the center of the painting. The colors are muted and the lighting is harsh, creating a sense of drama and tension. The figures are stiff and formal, and their expressions are stern and resolute. The background is composed of a brick wall and a vanishing point, which creates a sense of depth and perspective. The painting is a powerful statement about duty, honor, and sacrifice.",
} satisfies Vlrnabswgihxvvpbllpi

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default vlrnabswgihxvvpbllpi
