// This file is automatically generated. Do not modify manually.

export type Vymsrvvxwupdebwhkujr = {
  id: string
  image1: string
  image2: string
  description: string
}

const vymsrvvxwupdebwhkujr: Vymsrvvxwupdebwhkujr = {
  id: "vymsrvvxwupdebwhkujr",
  image1: "/images/vymsrvvxwupdebwhkujr-fijof.webp",
  image2: "/images/vymsrvvxwupdebwhkujr-rlvfq.webp",
  description:
    "The Luncheon by Claude Monet shows a table with a tea set on it. The woman in the painting is wearing a dress and holding a brooch. She is sitting at the table with her son. They are having a meal together. There is a book on the table. A lamp is hanging above the table. The tablecloth is white and has a pattern on it. The boy is wearing a hat. The woman is wearing a dress. There is a vase of flowers on the table. The table is covered with a cloth. The room is decorated with paintings. There is a window in the background. The painting is in the style of Impressionism.",
} satisfies Vymsrvvxwupdebwhkujr

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default vymsrvvxwupdebwhkujr
