// This file is automatically generated. Do not modify manually.

export type Wfnyemrkvsiicvroenmw = {
  id: string
  image1: string
  image2: string
  description: string
}

const wfnyemrkvsiicvroenmw: Wfnyemrkvsiicvroenmw = {
  id: "wfnyemrkvsiicvroenmw",
  image1: "/images/wfnyemrkvsiicvroenmw-gupef.webp",
  image2: "/images/wfnyemrkvsiicvroenmw-zowea.webp",
  description:
    "a painting of a woman in a white dress by Renoir.  \n\nA woman with a golden necklace and earrings sits in a lavish interior, surrounded by ornate furniture and velvet drapes, her face turned slightly to the side as she gazes out at the viewer with a subtle smile",
} satisfies Wfnyemrkvsiicvroenmw

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default wfnyemrkvsiicvroenmw
