// This file is automatically generated. Do not modify manually.

export type Wrtjvrhntrlvlqfbvcod = {
  id: string
  image1: string
  image2: string
  description: string
}

const wrtjvrhntrlvlqfbvcod: Wrtjvrhntrlvlqfbvcod = {
  id: "wrtjvrhntrlvlqfbvcod",
  image1: "/images/wrtjvrhntrlvlqfbvcod-sseig.webp",
  image2: "/images/wrtjvrhntrlvlqfbvcod-yexqd.webp",
  description:
    "In the painting La Promenade, a woman stands with her son and his father in a garden. The sun shines brightly on them as they walk together along a path through lush greenery. It is springtime and there are flowers blooming all around them. The woman wears a pink dress with white lace trim at the neckline and sleeves; she has blonde hair pulled back into a bun at the nape of her neck. Her face is lit from above by sunlight streaming through leaves overhead. She holds onto her young son's hand while he looks up at his father who walks behind them both wearing dark clothing including trousers, vest, jacket, tie, straw hat, mustache, moustache, eyebrows, sideburns, shoes, boots. They seem happy to be spending time together outdoors enjoying nature's beauty during this beautiful day in late May or early June.",
} satisfies Wrtjvrhntrlvlqfbvcod

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default wrtjvrhntrlvlqfbvcod
