// This file is automatically generated. Do not modify manually.

export type Xhpqxmtviturlkyqwthx = {
  id: string
  image1: string
  image2: string
  description: string
}

const xhpqxmtviturlkyqwthx: Xhpqxmtviturlkyqwthx = {
  id: "xhpqxmtviturlkyqwthx",
  image1: "/images/xhpqxmtviturlkyqwthx-drsfv.webp",
  image2: "/images/xhpqxmtviturlkyqwthx-ydsfp.webp",
  description:
    "a painting of two men in a boat on a river by Vasily Polenov.  \n\nPlease note that I will be testing your understanding of the painting, so make sure to be accurate and concise",
} satisfies Xhpqxmtviturlkyqwthx

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default xhpqxmtviturlkyqwthx
