// This file is automatically generated. Do not modify manually.

export type AnswersTest = {
  id: number
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: string | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}[]

const answersTest: AnswersTest = [
  {
    id: 0,
    artwork: {
      image:
        "https://upload.wikimedia.org/wikipedia/commons/5/59/Monet_-_Impression%2C_Sunrise.jpg",
      paintingLabel: "Impression, Sunrise",
      artistName: "Claude Monet",
      date_of_birth: "1840",
      date_of_death: "1926",
      image_of_artist:
        "https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg",
      movementLabel: "Impressionism",
      width: "63",
      height: "48",
      description: "painting by Claude Monet, 1872",
      abstract:
        "Impression, Sunrise (French: Impression, soleil levant) is a painting by Claude Monet first shown at what would become known as the 'Exhibition of the Impressionists' in Paris in April, 1874. The painting is credited with inspiring the name of the Impressionist movement. \\nImpression, Sunrise depicts the port of Le Havre, Monet's hometown. It is now displayed at the Musée Marmottan Monet in Paris.",
      depicts: [
        "light source",
        "aerial perspective",
        "factory chimney",
        "fisher",
        "Port of Le Havre",
        "barque",
        "spar",
        "smoke",
        "specular reflection",
        "sailboat",
        "haze",
        "sky",
        "crane",
        "Sun",
        "sea",
        "sunrise",
        "morning",
        "contre-jour",
      ],
    },
    prompt:
      "Painting in the style of Claude Monet.  \n\nPlease note that I will be checking your answer for accuracy and clarity",
    result: 1,
  },
  {
    id: 1,
    artwork: {
      image:
        "https://upload.wikimedia.org/wikipedia/commons/2/28/Claude_Monet_-_Cath%C3%A9drale_de_Rouen._Harmonie_bleue.jpg",
      paintingLabel: "Rouen Cathedral, Portal, Morning Sun",
      artistName: "Claude Monet",
      date_of_birth: "1840",
      date_of_death: "1926",
      image_of_artist:
        "https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg",
      movementLabel: "Impressionism",
      width: "63",
      height: "91",
      description: "painting by Claude Monet, 1893",
      depicts: ["Rouen", "cathedral", "Rouen Cathedral", "morning"],
    },
    prompt:
      "Painting in the style of Claude Monet.  \n\nDescription: A warm, golden light illuminates the intricate stone carvings and ornate architecture of a Gothic cathedral portal, with shadows cast across the stone floor and walls",
    result: 0,
  },
  {
    id: 2,
    artwork: {
      image:
        "https://upload.wikimedia.org/wikipedia/commons/a/a6/Manet%2C_Edouard_-_Blonde_Woman_with_Bare_Breasts.jpg",
      paintingLabel: "La Blonde aux seins nus",
      artistName: "Édouard Manet",
      date_of_birth: "1832",
      date_of_death: "1883",
      image_of_artist:
        "https://upload.wikimedia.org/wikipedia/commons/2/20/%C3%89douard_Manet%2C_en_buste%2C_de_face_-_Nadar.jpg",
      movementLabel: "Impressionism",
      width: "52",
      height: "62.5",
      description: "painting by Edouard Manet",
      abstract:
        "Blonde Woman with Bare Breasts (French: La Blonde aux seins nus) is a c.1878 painting by Édouard Manet, now in the Musée d'Orsay in Paris Contrary to its title, it shows a brunette.",
      depicts: [
        "hat",
        "nudity",
        "blond",
        "long hair",
        "veil",
        "nipple",
        "standing",
        "shirt",
        "breast",
        "areola",
        "woman",
        "toplessness",
        "chestnut hair",
        "flower",
      ],
    },
    prompt:
      "Painting in the style of Édouard Manet.  A young woman with a gentle face and full breasts sits on a rocky outcropping, her torso bare, with a distant landscape visible behind her",
    result: 1,
  },
] satisfies AnswersTest

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default answersTest
