// This file is automatically generated. Do not modify manually.

export type QuestionsTest = {
  id: number
  image1: string
  image2: string
  description: string
}[]

const questionsTest: QuestionsTest = [
  {
    id: 0,
    image1: "/images/impressionism0_3867cjj8cnrgj0cg6tnrnr6t4g.webp",
    image2: "/images/impressionism0.webp",
    description:
      "a painting of a boat on a body of water by Blanche Hoschedé Monet.  \n\nHere is my response:\n\nA hazy, yellow-orange sunrise illuminates the misty port of Le Havre, with the silhouette of a ship and a few buildings visible in the foreground",
  },
  {
    id: 1,
    image1: "/images/impressionism1.webp",
    image2: "/images/impressionism1_d00ntvycn5rgg0cg6tnvvpfb0w.webp",
    description:
      "a painting of a large cathedral with a sky background.  \n\nHere is the description:\n\nA large, stone Gothic cathedral with intricate carvings and ornate details stands tall, bathed in warm morning sunlight that casts long shadows across its façade",
  },
  {
    id: 2,
    image1: "/images/impressionism2_g1nkea3ajhrgj0cg6tpbr9tn1c.webp",
    image2: "/images/impressionism2.webp",
    description:
      "a painting of a woman with a hat on her head by Édouard Manet.  A young woman with golden hair and a serene expression sits nude on a couch, her arms wrapped around her knees, while a small dog lies at her feet",
  },
] satisfies QuestionsTest

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default questionsTest
