// This file is automatically generated. Do not modify manually.

export type Questions = {
  prompt: string
  promptOrigin: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    creationYear?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
  }
  machineUrl: string
  masterUrl: string
}[]

const questions: Questions = [
  {
    prompt:
      "a painting of a bowl of fruit on a table, a cubist painting by Gino Severini, pixiv, cubism, cubism, picasso, angular",
    promptOrigin: "prompt extracted from image",
    artwork: {
      image:
        "https://upload.wikimedia.org/wikipedia/commons/3/39/Pears_and_Grapes_on_a_Table.jpg",
      paintingLabel: "Pears and Grapes on a Table",
      artistName: "Juan Gris",
      date_of_birth: "1887",
      date_of_death: "1927",
      image_of_artist:
        "https://upload.wikimedia.org/wikipedia/commons/6/6c/Amedeo_Modigliani_-_Portrait_of_Juan_Gris.jpg",
      movementLabel: "Cubism",
      width: "73",
      height: "54.6",
      description: "painting by Juan Gris",
    },
    machineUrl:
      "/images/pearsAndGrapesOnATableXXXXJuanGris_hkmmwymxv1rgg0cg0cyrm25s1m.webp",
    masterUrl: "/images/pearsAndGrapesOnATableXXXXJuanGris.webp",
  },
  {
    prompt:
      "Pears and Grapes on a Table: An Cubism painting in the style of Juan Gris, painted in , Cubism, painting by Juan Gris, ",
    promptOrigin: "Manually build from artwork data",
    artwork: {
      image:
        "https://upload.wikimedia.org/wikipedia/commons/3/39/Pears_and_Grapes_on_a_Table.jpg",
      paintingLabel: "Pears and Grapes on a Table",
      artistName: "Juan Gris",
      date_of_birth: "1887",
      date_of_death: "1927",
      image_of_artist:
        "https://upload.wikimedia.org/wikipedia/commons/6/6c/Amedeo_Modigliani_-_Portrait_of_Juan_Gris.jpg",
      movementLabel: "Cubism",
      width: "73",
      height: "54.6",
      description: "painting by Juan Gris",
    },
    machineUrl:
      "/images/pearsAndGrapesOnATableXXXXJuanGris_hpmx87nag9rgp0cg0cyrdbs3qr.webp",
    masterUrl: "/images/pearsAndGrapesOnATableXXXXJuanGris.webp",
  },
] satisfies Questions

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default questions
