// This file is automatically generated. Do not modify manually.

export type AfricanAmericanArt = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const africanAmericanArt: AfricanAmericanArt = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/45/Moroccan_Scene_by_Henry_Ossawa_Tanner_-_BMA.jpg",
    paintingLabel: "Moroccan Scene",
    artistName: "Henry Ossawa Tanner",
    date_of_birth: "1859",
    date_of_death: "1937",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/7/7a/Henry_Ossawa_Tanner.jpg",
    movementLabel: "African American art",
    width: "15.25",
    height: "18.25",
    description: "painting by Henry Ossawa Tanner",
  },
] satisfies AfricanAmericanArt

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default africanAmericanArt
