// This file is automatically generated. Do not modify manually.

export type AmericanImpressionism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const americanImpressionism: AmericanImpressionism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/de/Seacoast_by_Edward_Moran.jpg",
    paintingLabel: "Seacoast",
    artistName: "Edward Moran",
    date_of_birth: "1829",
    date_of_death: "1901",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/f/fc/Edward_Moran.jpg",
    movementLabel: "American Impressionism",
    description: "painting by Edward Moran",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/95/Symphony_in_flesh_color_and_pink_by_JM_Whistler%2C_1871-74.jpg",
    paintingLabel:
      "Symphony in Flesh Colour and Pink: Portrait of Mrs Frances Leyland",
    artistName: "James Abbott McNeill Whistler",
    date_of_birth: "1834",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/e1/Whistler_Selbstportr%C3%A4t.jpg",
    movementLabel: "American Impressionism",
    width: "102.2",
    height: "195.9",
    description: "painting by James McNeill Whistler",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/37/Bathing_in_a_Stream_by_Robert_Reid.jpg",
    paintingLabel: "Bathing in a Stream",
    artistName: "Robert Lewis Reid",
    date_of_birth: "1862",
    date_of_death: "1929",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/2/26/Robert_L._Reid%2C_Ten_American_Painters_%28The_Ten%29_%28cropped%29.jpg",
    movementLabel: "American Impressionism",
    description: "painting by Robert Reid",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a2/Solitude_by_Ralph_Albert_Blakelock.jpg",
    paintingLabel: "Solitude",
    artistName: "Ralph Albert Blakelock",
    date_of_birth: "1847",
    date_of_death: "1919",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/86/Ralph_Albert_Blakelock.jpg",
    movementLabel: "American Impressionism",
    description: "painting by Ralph Albert Blakelock",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/85/Theodore_Earl_Butler_Flags_1918.jpg",
    paintingLabel: "Flags",
    artistName: "Theodore Earl Butler",
    date_of_birth: "1861",
    date_of_death: "1936",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/8a/Portrait_of_Butler.jpg",
    movementLabel: "American Impressionism",
    width: "27.25",
    height: "42.25",
    description: "painting by Theodore Earl Butler",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/ac/Arrangement_in_black_and_gold.jpg",
    paintingLabel:
      "Arrangement in Black and Gold: Comte Robert de Montesquiou-Fezensac",
    artistName: "James Abbott McNeill Whistler",
    date_of_birth: "1834",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/e1/Whistler_Selbstportr%C3%A4t.jpg",
    movementLabel: "American Impressionism",
    description: "painting by James McNeill Whistler",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/93/Childe_Hassam_-_Building_a_Schooner%2C_Provincetown.JPG",
    paintingLabel: "Building the Schooner, Provincetown",
    artistName: "Childe Hassam",
    date_of_birth: "1859",
    date_of_death: "1935",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/82/Childe_Hassam_1903.png",
    movementLabel: "American Impressionism",
    description: "painting by Childe Hassam",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c3/New_England_Landscape_by_Alfred_Thompson_Bricher.jpg",
    paintingLabel: "New England Landscape",
    artistName: "Alfred Thompson Bricher",
    date_of_birth: "1837",
    date_of_death: "1908",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/e3/Alfred_Thompson_Bricher.jpg",
    movementLabel: "American Impressionism",
    description: "painting by Alfred Thompson Bricher",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Seascape_with_Boats_by_William_Merritt_Chase.jpg",
    paintingLabel: "Dutch Boats at Anchor",
    artistName: "Harry Chase",
    date_of_birth: "1853",
    date_of_death: "1889",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Harry_Chase_%281883_portrait%29.jpg",
    movementLabel: "American Impressionism",
    width: "32",
    height: "13",
    description: "painting by Harry Chase",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/93/Hassam%2C_Childe_-_Cliff_Rock_-_Appledore_-_Google_Art_Project.jpg",
    paintingLabel: "Cliff Rock--Appledore",
    artistName: "Childe Hassam",
    date_of_birth: "1859",
    date_of_death: "1935",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/82/Childe_Hassam_1903.png",
    movementLabel: "American Impressionism",
    width: "36",
    height: "29",
    description: "painting by Childe Hassam",
    abstract:
      "Cliff Rock - Appledore is an oil painting by American artist Childe Hassam, painted in 1903. It is currently part of the permanent collection at the Indianapolis Museum of Art.",
  },
  {
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d2/2001.11.jpg",
    paintingLabel: "Under a French Sky",
    artistName: "William Merritt Chase",
    date_of_birth: "1849",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a7/William_Merritt_Chase.jpg",
    movementLabel: "American Impressionism",
    width: "24.1",
    height: "63.5",
    description: "painting by William Merritt Chase",
  },
] satisfies AmericanImpressionism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default americanImpressionism
