// This file is automatically generated. Do not modify manually.

export type AmericanRealism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const americanRealism: AmericanRealism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d9/Winslow_Homer_-_The_Brierwood_Pipe_-_1944.524_-_Cleveland_Museum_of_Art.tiff",
    paintingLabel: "The Brierwood Pipe",
    artistName: "Winslow Homer",
    date_of_birth: "1836",
    date_of_death: "1910",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/05/WinslowHomer.jpeg",
    movementLabel: "American realism",
    width: "64.13",
    height: "68.89",
    description: "painting by Winslow Homer",
    abstract:
      "The Brierwood Pipe, 1864 is an oil painting by Winslow Homer of two men from the 5th New York Volunteer Infantry (Duryee Zouaves).\\nThe title may refer to a popular poem of the day about the 5th New York Zouaves, titled 'The Brier-Wood Pipe.' 'Two of the most famous Zouave outfits in the Army of the Potomac were from New York, Duryees and Hawkins's.'It is also known as Making Brier-root Pipes, Making Brierwood Pipes, and other similar variants.\\nAs of 2012, the painting is on display at the Smithsonian American Art Museum, from the collection of the Cleveland Museum of Art.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/ae/Early-sunday-morning-edward-hopper-1930.jpg",
    paintingLabel: "Early Sunday Morning",
    artistName: "Edward Hopper",
    date_of_birth: "1882",
    date_of_death: "1967",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b7/Edward_Hopper%2C_New_York_artist_LCCN2016871478_%28cropped%29.jpg",
    movementLabel: "American realism",
    width: "153",
    height: "89.4",
    description: "painting by Edward Hopper",
    abstract:
      "Early Sunday Morning is a 1930 painting by American artist Edward Hopper.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg",
    paintingLabel: "Nighthawks",
    artistName: "Edward Hopper",
    date_of_birth: "1882",
    date_of_death: "1967",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b7/Edward_Hopper%2C_New_York_artist_LCCN2016871478_%28cropped%29.jpg",
    movementLabel: "American realism",
    width: "152.4",
    height: "84.1",
    description: "1942 oil on canvas painting by Edward Hopper",
    abstract:
      "Nighthawks is a 1942 oil on canvas painting by Edward Hopper that portrays people in a downtown diner late at night as viewed through the diner's large glass window. Also portrayed are the exteriors of the urban structures across the street from the diner. \\nIt has been described as Hopper's best-known work and is one of the most recognizable paintings in American art. Within months of its completion, it was sold to the Art Institute of Chicago on May 13, 1942 for $3,000.",
  },
] satisfies AmericanRealism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default americanRealism
