// This file is automatically generated. Do not modify manually.

export type AmsterdamImpressionism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const amsterdamImpressionism: AmsterdamImpressionism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/45/De_schelpenvisser_Rijksmuseum_SK-A-3349.jpeg",
    paintingLabel: "De schelpenvisser",
    artistName: "Jan Toorop",
    date_of_birth: "1858",
    date_of_death: "1928",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Fotoportret_van_Jan_Toorop.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "32",
    height: "40",
    description: "painting by Jan Toorop",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/41/Jan_Toorop_-_Vrowen_aan_Zee.jpg",
    paintingLabel: "Vrouwen aan zee",
    artistName: "Jan Toorop",
    date_of_birth: "1858",
    date_of_death: "1928",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Fotoportret_van_Jan_Toorop.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "46",
    height: "36",
    description: "painting by Jan Toorop",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/90/Stilleven_met_appels_op_een_Delfts_blauwe_schaal_Rijksmuseum_SK-A-3361.jpeg",
    paintingLabel: "Still Life with Apples in a Delft Blue Bowl",
    artistName: "Willem de Zwart",
    date_of_birth: "1862",
    date_of_death: "1931",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/db/Willem_de_zwart.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "79",
    height: "48.5",
    description: "painting by Willem de Zwart",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c4/Annie_Hall_te_Lissadell%2C_Surrey_Rijksmuseum_SK-C-1666.jpeg",
    paintingLabel: "Portrait of Annie Hall",
    artistName: "Jan Toorop",
    date_of_birth: "1858",
    date_of_death: "1928",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Fotoportret_van_Jan_Toorop.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "73",
    height: "99",
    description: "painting by Jan Toorop, 1885",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/30/Willem_de_Zwart_-_Hooiwagen.jpg",
    paintingLabel: "Hay Wagon",
    artistName: "Willem de Zwart",
    date_of_birth: "1862",
    date_of_death: "1931",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/db/Willem_de_zwart.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "24.7",
    height: "17.5",
    description: "painting by Willem de Zwart",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/13/Jan_Toorop_-_De_zee_bij_Katwijk_-_SK-A-4226_-_Rijksmuseum.jpg",
    paintingLabel: "The Sea near Katwijk",
    artistName: "Jan Toorop",
    date_of_birth: "1858",
    date_of_death: "1928",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Fotoportret_van_Jan_Toorop.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "96",
    height: "86",
    description: "painting by Jan Toorop",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3e/Isaac_Israels_-_Woman_before_%27%27Sunflowers%27%27_by_van_Gogh%2C_1917.JPG",
    paintingLabel: "Woman before Sunflowers",
    artistName: "Isaac Israëls",
    date_of_birth: "1865",
    date_of_death: "1934",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/2/2b/Isaac_Isra%C3%ABls_-_Zelfportret_met_doek_van_Javaanse_prins_Jodjana.jpg",
    movementLabel: "Amsterdam Impressionism",
    description: "painting by Isaac Israëls",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/Willem_de_Zwart_%281862-1931%29_-_Carriages_Waiting_%28Unknown%29.jpg",
    paintingLabel: "Carriages Waiting",
    artistName: "Willem de Zwart",
    date_of_birth: "1862",
    date_of_death: "1931",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/db/Willem_de_zwart.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "43",
    height: "31.5",
    description: "painting by Willem de Zwart",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Isaac_Isra%C3%ABls_-_Two_models%2C_Epi_and_Gertie%2C_in_the_Amsterdam_Fashion_House_Hirsch.jpg",
    paintingLabel:
      "Two models, Epi and Gertie, in the Amsterdam Fashion House Hirsch",
    artistName: "Isaac Israëls",
    date_of_birth: "1865",
    date_of_death: "1934",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/2/2b/Isaac_Isra%C3%ABls_-_Zelfportret_met_doek_van_Javaanse_prins_Jodjana.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "51",
    height: "78.5",
    description: "painting by Isaac Israëls",
    abstract:
      "Ippy and Gertie Posing at Fashion House Hirsch, Amsterdam is a circa 1916 oil on canvas painting by the Dutch artist Isaac Israëls. It depicts the twin sisters Helena (1895-1964) and Geertruida Wehmann (1895-1975), models at the Amsterdam fashion house Hirsch & Cie in the Leidseplein whose professional names were Ippy and Gertie respectively.\\nIsraëls was introduced to the house by his childhood friend and portrait painter Thérèse Schwartze. He went on to portray the whole range of the world of haute couture, both in Amsterdam and Paris. His treatment is realist rather than glamorous, portraying seamstresses as well as their wealthy clients.\\nHirsch & Cie in Amsterdam continued until 1943, when it was forced to close as part of the Nazi policy of dispossessing Jews of their property during the occupation of the Netherlands. It re-opened in 1948 after the war and continued until 1976 when it finally closed its doors. The premises are now occupied by an Apple Store.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/f2/George_Hendrik_Breitner_-_The_Singelbrug_near_the_Paleisstraat_in_Amsterdam.jpg",
    paintingLabel: "The Singel Bridge at the Paleisstraat in Amsterdam",
    artistName: "George Hendrik Breitner",
    date_of_birth: "1857",
    date_of_death: "1923",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/5/50/George_Hendrik_Breitner_-_Self-portrait_with_pince-nez_-_Google_Art_Project.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "152",
    height: "100",
    description: "painting by George Hendrik Breitner",
    abstract:
      "The Singel Bridge at the Paleisstraat in Amsterdam (Dutch: De Singelbrug bij de Paleisstraat in Amsterdam) is an oil painting made by George Hendrik Breitner in 1896 or 1898. The painting shows people walking on the Singel Bridge at the Paleisstraat in Amsterdam. The work is oil on canvas of 100 cm (39 in) by 152 cm (60 in). The painting is in the collection of the Rijksmuseum in Amsterdam.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/72/Willem_Bastiaan_Tholen_-_Het_Slachthuis.jpg",
    paintingLabel: "Het slachthuis",
    artistName: "Willem Bastiaan Tholen",
    date_of_birth: "1860",
    date_of_death: "1931",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/5/5b/Willem_Bastiaan_Tholen_zelfportret_1914.jpg",
    movementLabel: "Amsterdam Impressionism",
    width: "71",
    height: "57",
    description: "painting by Willem Bastiaan Tholen",
  },
] satisfies AmsterdamImpressionism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default amsterdamImpressionism
