// This file is automatically generated. Do not modify manually.

export type ArtOfAncientEgypt = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const artOfAncientEgypt: ArtOfAncientEgypt = [] satisfies ArtOfAncientEgypt

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default artOfAncientEgypt
