// This file is automatically generated. Do not modify manually.

export type Bamboccianti = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const bamboccianti: Bamboccianti = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/25/Berchem_Catching_crayfish.jpg",
    paintingLabel: "Catching crayfish.",
    artistName: "Nicolaes Pieterszoon Berchem",
    date_of_birth: "1622",
    date_of_death: "1683",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/7/74/Nicolaes_Berchem_-_Portrait.jpg",
    movementLabel: "Bamboccianti",
    width: "43.5",
    height: "45",
    description: "painting by Nicolaes Pieterszoon Berchem",
  },
] satisfies Bamboccianti

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default bamboccianti
