// This file is automatically generated. Do not modify manually.

export type BaroqueSculpture = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const baroqueSculpture: BaroqueSculpture = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/81/Coustou_Bust_of_a_court_lady_01.jpg",
    paintingLabel:
      "Bust of a court lady by Guillaume Coustou (National Museum in Warsaw)",
    artistName: "Guillaume Coustou the Elder",
    date_of_birth: "1677",
    date_of_death: "1746",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Guillaume_Coustou.jpg",
    movementLabel: "Baroque sculpture",
    height: "72",
    description: "Skulptur von Guillaume Coustou der Ältere (German)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/89/Varin_Bust_of_Louis_XIV_of_France_01.jpg",
    paintingLabel:
      "Bust of Louis XIV of France by Jean Varin (National Museum in Warsaw)",
    artistName: "Jean Varin",
    date_of_birth: "1607",
    date_of_death: "1672",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a1/Jean_Varin_by_Adolphe_Varin.jpg",
    movementLabel: "Baroque sculpture",
    height: "58",
    description: "Skulptur von Jean Varin (German)",
  },
] satisfies BaroqueSculpture

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default baroqueSculpture
