// This file is automatically generated. Do not modify manually.

export type Cloisonnism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const cloisonnism: Cloisonnism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Gauguin_Il_Cristo_giallo.jpg",
    paintingLabel: "The Yellow Christ",
    artistName: "Paul Gauguin",
    date_of_birth: "1848",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/Paul_Gauguin_111.jpg",
    movementLabel: "Cloisonnism",
    width: "73.4",
    height: "91.1",
    description: "painting by Paul Gauguin",
    abstract:
      "The Yellow Christ (in French: Le Christ jaune) is a painting executed by Paul Gauguin in 1889 in Pont-Aven. Together with The Green Christ, it is considered to be one of the key works of Symbolism in painting.\\n\\nGauguin first visited Pont-Aven in 1886. He returned to the village in early 1888 to stay until mid-October, when he left to join Vincent van Gogh in Arles, for little more than two months. Early in 1889, Gauguin was back to Pont-Aven to stay there until spring 1890. It was only for a short visit in summer 1889 to Paris to see the Exposition universelle and to arrange the Volpini Exhibition that Gauguin interrupted this sojourn. Soon after his return to Pont-Aven he painted The Yellow Christ:\\nThe Yellow Christ is a symbolic piece that shows the crucifixion of Christ taking place in nineteenth-century northern France as Breton women are gathered in prayer. Gauguin relies heavily on bold lines to define his figures and reserves shading only for the women. The autumn palette of yellow, red and green in the landscape echoes the dominant yellow in the figure of Christ. The bold outlines and flatness of the forms in this painting are typical of the cloisonnist style. \\nA study for The Yellow Christ in pencil is preserved in the Thyssen-Bornemisza Museum, and a version in watercolor is in the collection of the Art Institute of Chicago, gift of Elizabeth F. Chapman.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Van_Gogh_-_Tanzsaal_in_Arles.jpg",
    paintingLabel: "Dance Hall in Arles",
    artistName: "Vincent van Gogh",
    date_of_birth: "1853",
    date_of_death: "1890",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/aa/Vincent_van_Gogh_-_Self-portrait_with_grey_felt_hat_-_Google_Art_Project.jpg",
    movementLabel: "Cloisonnism",
    width: "810",
    height: "650",
    description: "painting by Vincent van Gogh",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/85/Gauguin%2C_Paul_-_Still_Life_with_Profile_of_Laval_-_Google_Art_Project.jpg",
    paintingLabel: "Still Life with Profile of Laval",
    artistName: "Paul Gauguin",
    date_of_birth: "1848",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/Paul_Gauguin_111.jpg",
    movementLabel: "Cloisonnism",
    width: "15",
    height: "18.125",
    description: "painting by Paul Gauguin",
    abstract:
      "Still Life with Profile of Laval is an 1886 oil painting by French artist Paul Gauguin, located in the Indianapolis Museum of Art, which is in Indianapolis, Indiana. It depicts Gauguin's friend Charles Laval in profile with an assortment of inanimate objects, including a ceramic pot Gauguin made himself.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/%C3%89mile_Bernard_-_Les_femmes_bretonnes_%C3%A0_la_pri%C3%A8re.jpg",
    paintingLabel: "Breton Women Attending a Pardon",
    artistName: "Émile Bernard",
    date_of_birth: "1868",
    date_of_death: "1941",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/e4/Henri_de_Toulouse-Lautrec_-_Portrait_de_%C3%89mile_Bernard.jpg",
    movementLabel: "Cloisonnism",
    width: "116.21",
    height: "82.25",
    description: "painting by Emile Bernard",
  },
] satisfies Cloisonnism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default cloisonnism
