// This file is automatically generated. Do not modify manually.

export type Flexibility = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const flexibility: Flexibility = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/56/Austerlitz-baron-Pascal.jpg",
    paintingLabel: "The Battle of Austerlitz, 2nd December 1805",
    artistName: "François Gérard",
    date_of_birth: "1770",
    date_of_death: "1837",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/Fran%C3%A7ois_G%C3%A9rard_%281770%E2%80%931837%29%2C_later_Baron_G%C3%A9rard_MET_DP327712.jpg",
    movementLabel: "flexibility",
    width: "958",
    height: "510",
    description: "painting by François Gérard",
  },
] satisfies Flexibility

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default flexibility
