// This file is automatically generated. Do not modify manually.

export type GothicSculpture = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const gothicSculpture: GothicSculpture = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3a/Tino_di_Camaino%2C_battesimo_di_cristo_01.JPG",
    paintingLabel: "The Baptism of Christ",
    artistName: "Tino di Camaino",
    date_of_birth: "1285",
    date_of_death: "1337",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tino_di_camaino%2C_angelo%2C_1300-1325_ca.%2C_da_palazzo_bargagli_petrucci_tempi%2C_03.JPG",
    movementLabel: "Gothic sculpture",
    description: "sculpture by Tino di Camaino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/39/Karl_von_Anjou.JPG",
    paintingLabel: "Monument to Charles I of Anjou by Arnolfo di Cambio",
    artistName: "Arnolfo di Cambio",
    date_of_birth: "1240",
    date_of_death: "1302",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Vite_de_pi%C3%B9_eccellenti_pittori_scultori_ed_architetti_%281767%29_%2814597572560%29.jpg",
    movementLabel: "Gothic sculpture",
    height: "160",
    description: "sculpture by Arnolfo di Cambio",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/78/Arnolfo_di_cambio%2C_dormitio_virginis_con_frammento_di_teste%2C_dalla_facciata_di_sm_del_fiore%2C_1300_ca..JPG",
    paintingLabel: "Dormitio Virginis",
    artistName: "Arnolfo di Cambio",
    date_of_birth: "1240",
    date_of_death: "1302",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Vite_de_pi%C3%B9_eccellenti_pittori_scultori_ed_architetti_%281767%29_%2814597572560%29.jpg",
    movementLabel: "Gothic sculpture",
    width: "177",
    height: "60",
    description: "sculpture by Arnolfo di Cambio",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/38/Barcelona_Cathedral_Interior_-_Ark_of_Santa_Eulalia.jpg",
    paintingLabel: "Ark of Santa Eulalia",
    artistName: "Lupo di Francesco",
    date_of_birth: "1201",
    date_of_death: "1400",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/38/Barcelona_Cathedral_Interior_-_Ark_of_Santa_Eulalia.jpg",
    movementLabel: "Gothic sculpture",
    description: "tombe d'Eulalie de Barcelone (French)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/fb/Tino_di_Camaino%2C_Fede_01.JPG",
    paintingLabel: "Faith",
    artistName: "Tino di Camaino",
    date_of_birth: "1285",
    date_of_death: "1337",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tino_di_camaino%2C_angelo%2C_1300-1325_ca.%2C_da_palazzo_bargagli_petrucci_tempi%2C_03.JPG",
    movementLabel: "Gothic sculpture",
    width: "46",
    height: "64",
    description: "sculpture by Tino di Camaino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/37/Carit%C3%A0_di_Tino_di_Camaino2.JPG",
    paintingLabel: "Charity",
    artistName: "Tino di Camaino",
    date_of_birth: "1285",
    date_of_death: "1337",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tino_di_camaino%2C_angelo%2C_1300-1325_ca.%2C_da_palazzo_bargagli_petrucci_tempi%2C_03.JPG",
    movementLabel: "Gothic sculpture",
    width: "71",
    height: "136",
    description: "sculpture by Tino di Camaino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/f6/South_Doors_of_the_Florence_Baptistry.JPG",
    paintingLabel: "South Doors of the Florence Baptistery",
    artistName: "Andrea Pisano",
    date_of_birth: "1290",
    date_of_death: "1348",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/08/011_le_vite%2C_andrea_pisano.jpg",
    movementLabel: "Gothic sculpture",
    width: "428",
    height: "577",
    description: "sculpture by Andrea Pisano",
  },
  {
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Lunetta_2.JPG",
    paintingLabel: "Madonna dagli occhi di vetro",
    artistName: "Arnolfo di Cambio",
    date_of_birth: "1240",
    date_of_death: "1302",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Vite_de_pi%C3%B9_eccellenti_pittori_scultori_ed_architetti_%281767%29_%2814597572560%29.jpg",
    movementLabel: "Gothic sculpture",
    width: "72",
    height: "173",
    description: "sculpture by Arnolfo di Cambio",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/Tino_di_Camaino%2C_testa_del_battista_01.JPG",
    paintingLabel: "Head of Saint John the Baptist",
    artistName: "Tino di Camaino",
    date_of_birth: "1285",
    date_of_death: "1337",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tino_di_camaino%2C_angelo%2C_1300-1325_ca.%2C_da_palazzo_bargagli_petrucci_tempi%2C_03.JPG",
    movementLabel: "Gothic sculpture",
    description: "sculpture by Tino di Camaino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b1/Tino_di_Camaino%2C_Speranza_01.JPG",
    paintingLabel: "Hope",
    artistName: "Tino di Camaino",
    date_of_birth: "1285",
    date_of_death: "1337",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tino_di_camaino%2C_angelo%2C_1300-1325_ca.%2C_da_palazzo_bargagli_petrucci_tempi%2C_03.JPG",
    movementLabel: "Gothic sculpture",
    width: "21",
    height: "33",
    description: "sculpture by Tino di Camaino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6e/Tino_di_Camaino%2C_Sibilla_01.JPG",
    paintingLabel: "Sibyl",
    artistName: "Tino di Camaino",
    date_of_birth: "1285",
    date_of_death: "1337",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tino_di_camaino%2C_angelo%2C_1300-1325_ca.%2C_da_palazzo_bargagli_petrucci_tempi%2C_03.JPG",
    movementLabel: "Gothic sculpture",
    height: "65",
    description: "sculpture by Tino di Camaino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/cf/Andrea_Pisano%2C_Madonna_del_latte.jpg",
    paintingLabel: "Nursing Madonna",
    artistName: "Andrea Pisano",
    date_of_birth: "1290",
    date_of_death: "1348",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/08/011_le_vite%2C_andrea_pisano.jpg",
    movementLabel: "Gothic sculpture",
    description: "sculpture by Andrea Pisano",
    abstract:
      "Nursing Madonna (Italian - Madonna del Latte) is a 14th-century marble sculpture by Andrea Pisano, possibly with some involvement from his son Nino Pisano, originally produced for a niche at the church of Santa Maria della Spina but now in the Museo Nazionale di San Matteo in Pisa.",
  },
] satisfies GothicSculpture

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default gothicSculpture
