// This file is automatically generated. Do not modify manually.

export type GreekLateClassicalPeriod = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const greekLateClassicalPeriod: GreekLateClassicalPeriod = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/98/Afrodite_cnidia.jpg",
    paintingLabel: "Aphrodite of Knidos",
    artistName: "Praxiteles",
    date_of_birth: "-395",
    date_of_death: "-330",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/f/f8/Edifici_carrer_Tallers_45_Barcelona_-_03_Praxiteles.JPG",
    movementLabel: "Greek late classical period",
    height: "205",
    description: "sculpture of Greek sculptor Praxiteles of Athens",
    abstract:
      "The Aphrodite of Knidos (or Cnidus) was an Ancient Greek sculpture of the goddess Aphrodite created by Praxiteles of Athens around the 4th century BCE.  It is one of the first life-sized representations of the nude female form in Greek history, displaying an alternative idea to male heroic nudity. Praxiteles' Aphrodite is shown nude, reaching for a bath towel while covering her pubis, which, in turn leaves her breasts exposed. Up until this point, Greek sculpture had been dominated by male nude figures.  The original Greek sculpture is no longer in existence; however, many Roman copies survive of this influential work of art. Variants of the Venus Pudica (suggesting an action to cover the breasts) are the Venus de' Medici and the Capitoline Venus.",
  },
] satisfies GreekLateClassicalPeriod

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default greekLateClassicalPeriod
