// This file is automatically generated. Do not modify manually.

export type ItalianMannerismPainting = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const italianMannerismPainting: ItalianMannerismPainting = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c9/Lavinia_Fontana%27s_%27Newborn_Baby_in_a_Crib%27_%28c._1583%29.jpg",
    paintingLabel: "Newborn Baby in a Crib",
    artistName: "Lavinia Fontana",
    date_of_birth: "1552",
    date_of_death: "1614",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a1/Lav_Fontana_Autoritratto.jpg",
    movementLabel: "Italian Mannerism painting",
    width: "126",
    height: "113",
    description: "painting of Lavinia Fontana",
  },
] satisfies ItalianMannerismPainting

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default italianMannerismPainting
