// This file is automatically generated. Do not modify manually.

export type ItalianBaroqueArt = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const italianBaroqueArt: ItalianBaroqueArt = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/30/Saint_Lucy_by_Artemisia_Gentileschi_ca._1642-1644.jpg",
    paintingLabel: "Saint Lucy",
    artistName: "Artemisia Gentileschi",
    date_of_birth: "1593",
    date_of_death: "1653",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/32/Artemisia_Gentileschi_Selfportrait_Martyr.jpg",
    movementLabel: "Italian Baroque art",
    width: "57",
    height: "74.4",
    description: "Attributed picture by Artemisia Gentileschi",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/77/Saint_Apollonia_by_Artemisia_Gentileschi_ca._1642-1644.jpg",
    paintingLabel: "Saint Apollonia",
    artistName: "Artemisia Gentileschi",
    date_of_birth: "1593",
    date_of_death: "1653",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/32/Artemisia_Gentileschi_Selfportrait_Martyr.jpg",
    movementLabel: "Italian Baroque art",
    width: "57",
    height: "74",
    description: "Picture by Artemisia Gentileschi",
    abstract:
      "Saint Apollonia is a painting attributed to the Italian baroque painter Artemisia Gentileschi executed between 1642 and 1644. It is part of the collection of the Museo Soumaya in Mexico City, Mexico.",
  },
] satisfies ItalianBaroqueArt

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default italianBaroqueArt
