// This file is automatically generated. Do not modify manually.

export type NeoclassicalSculpture = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const neoclassicalSculpture: NeoclassicalSculpture = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6d/Este_Antonina_Krasi%C5%84ska_01.jpg",
    paintingLabel: "Bust of Antonina Krasińska by Antonio d'Este",
    artistName: "Antonio D'Este",
    date_of_birth: "1754",
    date_of_death: "1837",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a1/Accademia_-_Antonio_d%27Este_%28Self_Portrait%29_-_1812-1815_CAT.S.24.jpg",
    movementLabel: "Neoclassical sculpture",
    height: "52",
    description: "Skulptur von Antonio D'Este (German)",
  },
] satisfies NeoclassicalSculpture

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default neoclassicalSculpture
