// This file is automatically generated. Do not modify manually.

export type NeueKNstlervereinigungMNchen = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const neueKNstlervereinigungMNchen: NeueKNstlervereinigungMNchen = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/64/Murnau%2C_Landschaft_mit_Turm.jpg",
    paintingLabel: "Murnau, Landscape with a Tower",
    artistName: "Wassily Kandinsky",
    date_of_birth: "1866",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/8a/Vassily-Kandinsky.jpeg",
    movementLabel: "Neue Künstlervereinigung München",
    width: "98.5",
    height: "74",
    description: "painting by Wassily Kandinsky",
  },
] satisfies NeueKNstlervereinigungMNchen

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default neueKNstlervereinigungMNchen
