// This file is automatically generated. Do not modify manually.

export type NorthernMannerism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const northernMannerism: NorthernMannerism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d8/All%C3%A9gorie_du_Temps.jpg",
    paintingLabel: "Allégorie du Temps",
    artistName: "Otto van Veen",
    date_of_birth: "1556",
    date_of_death: "1629",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/2/24/Gertruida_van_Veen_-_Portrait_of_the_painter_Otto_van_Veen.jpg",
    movementLabel: "Northern Mannerism",
    width: "45",
    height: "34",
    description: "painting by Otto Van Veen",
  },
] satisfies NorthernMannerism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default northernMannerism
