// This file is automatically generated. Do not modify manually.

export type Orientalis = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const orientalis: Orientalis = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/8d/Delacroix_lion_hunt_1855.JPG",
    paintingLabel: "The Lion Hunt",
    artistName: "Eugène Delacroix",
    date_of_birth: "1798",
    date_of_death: "1863",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/13/Eug%C3%A8ne_Ferdinand_Victor_Delacroix_051.jpg",
    movementLabel: "Orientalis",
    width: "74",
    height: "57",
    description: "painting by Eugène Delacroix",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/5a/Anders_Zorn_-_Kaikroddare.jpg",
    paintingLabel: "Kaikroddare",
    artistName: "Anders Zorn",
    date_of_birth: "1860",
    date_of_death: "1920",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Zornself.jpg",
    movementLabel: "Orientalis",
    description: "painting by Anders Zorn",
  },
] satisfies Orientalis

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default orientalis
