// This file is automatically generated. Do not modify manually.

export type Orphism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const orphism: Orphism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c9/August_macke-girl_with_a_fish_bowl.jpg",
    paintingLabel: "Mädchen mit Fischglas",
    artistName: "August Macke",
    date_of_birth: "1887",
    date_of_death: "1914",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b2/August_Macke_042.jpg",
    movementLabel: "Orphism",
    width: "100.5",
    height: "81",
    description: "painting by August Macke",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/33/12_fev_14_delaunay.jpg",
    paintingLabel: "Eiffel Tower",
    artistName: "Robert Delaunay",
    date_of_birth: "1885",
    date_of_death: "1941",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/48/Robert_Delaunay_portrait_photograph.jpg",
    movementLabel: "Orphism",
    width: "174",
    height: "184",
    description: "painting by Robert Delaunay (Dallas Museum of Art)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/46/Robert_delaunay%2C_una_finestra%2C_1912.JPG",
    paintingLabel: "Window",
    artistName: "Robert Delaunay",
    date_of_birth: "1885",
    date_of_death: "1941",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/48/Robert_Delaunay_portrait_photograph.jpg",
    movementLabel: "Orphism",
    width: "90",
    height: "111",
    description: "painting by Robert Delaunay",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/dd/Robert_Delaunay%2C_Rythmes%2C_1934.jpg",
    paintingLabel: "Rhythms",
    artistName: "Robert Delaunay",
    date_of_birth: "1885",
    date_of_death: "1941",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/48/Robert_Delaunay_portrait_photograph.jpg",
    movementLabel: "Orphism",
    width: "113",
    height: "145",
    description: "painting by Robert Delaunay (1934)",
    abstract:
      "Rhythms (in French: Rythmes) is a painting by the French artist Robert Delaunay from 1934.The picture is painted in oil on canvas. It was inspired by the round shapes that marked the return of the artist to orphism and study of harmony in painting. Its dimensions are 145 x 113 cm. The picture is part of the collection of the Centre Georges Pompidou.",
  },
] satisfies Orphism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default orphism
