// This file is automatically generated. Do not modify manually.

export type SchoolOfParis = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const schoolOfParis: SchoolOfParis = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c5/Amedeo_Modigliani_025.jpg",
    paintingLabel: "Jeanne Hébuterne in yellow sweater",
    artistName: "Amedeo Modigliani",
    date_of_birth: "1884",
    date_of_death: "1920",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/07/Amedeo-modigliani-identification-photo-nice-1918.jpg",
    movementLabel: "School of Paris",
    width: "65",
    height: "100",
    description: "painting by Amedeo Modigliani",
  },
] satisfies SchoolOfParis

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default schoolOfParis
