// This file is automatically generated. Do not modify manually.

export type SpanishGoldenAge = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const spanishGoldenAge: SpanishGoldenAge = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/f9/Bartolom%C3%A9_Esteban_Perez_Murillo_-_Trauben-_und_Melonenesser.jpg",
    paintingLabel: "Boys Eating Grapes and Melon",
    artistName: "Bartolomé Esteban Murillo",
    date_of_birth: "1617",
    date_of_death: "1682",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Murillo_Self-portrait.jpg",
    movementLabel: "Spanish Golden Age",
    width: "103.6",
    height: "145.9",
    description: "painting by Bartolomé Esteban Murillo",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/ff/El_Greco_-_The_Burial_of_the_Count_of_Orgaz.JPG",
    paintingLabel: "The Burial of the Count of Orgaz",
    artistName: "El Greco",
    date_of_birth: "1541",
    date_of_death: "1614",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/eb/El_Greco_-_Portrait_of_a_Man_-_WGA10554.jpg",
    movementLabel: "Spanish Golden Age",
    width: "360",
    height: "480",
    description: "painting by El Greco",
    abstract:
      "The Burial of the Count of Orgaz (Spanish: El Entierro del Conde de Orgaz) is a 1586 painting by El Greco, a prominent Renaissance painter, sculptor, and architect of Greek origin. Widely considered among his finest works, it illustrates a popular local legend of his time. An exceptionally large painting, it is divided into two sections, heavenly above and terrestrial below, but it gives little impression of duality, since the upper and lower sections are brought together compositionally.\\nThe painting has been lauded by art scholars, characterized, inter alia, as 'one of the most truthful pages in the history of Spain', as a masterpiece of Western Art and of late Mannerism, and as the epitome of Greco's artistic style.",
  },
] satisfies SpanishGoldenAge

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default spanishGoldenAge
