// This file is automatically generated. Do not modify manually.

export type TardoRomanticismoItalian = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const tardoRomanticismoItalian: TardoRomanticismoItalian = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a3/Carl_Spitzweg_025.jpg",
    paintingLabel: "The Geologist",
    artistName: "Carl Spitzweg",
    date_of_birth: "1808",
    date_of_death: "1885",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/6/63/Carl_Spitzweg_-_Selbstbildnis_%28ca._1842%29.jpg",
    movementLabel: "Tardo Romanticismo (Italian)",
    width: "34.5",
    height: "44",
    description: "painting by Carl Spitzweg",
  },
] satisfies TardoRomanticismoItalian

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default tardoRomanticismoItalian
