// This file is automatically generated. Do not modify manually.

export type TroubadourStyle = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const troubadourStyle: TroubadourStyle = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/14/Le_Jeune_Gaston%2C_dit_l%27ange_de_Foix_-_Claudius_Jacquand_-_MBA_Lyon_2014.jpg",
    paintingLabel: "Le Jeune Gaston, dit l'ange de Foix by Claudius Jacquand",
    artistName: "Claudius Jacquand",
    date_of_birth: "1803",
    date_of_death: "1878",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/Claudius_Jacquand.jpeg",
    movementLabel: "Troubadour style",
    width: "205",
    height: "162",
    description: "painting by Claudius Jacquand",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Jean_Auguste_Dominique_Ingres_-_The_Entry_of_the_Future_Charles_V_into_Paris_in_1358_-_WGA11847.jpg",
    paintingLabel: "The Dauphin's Entry Into Paris",
    artistName: "Jean Auguste Dominique Ingres",
    date_of_birth: "1780",
    date_of_death: "1867",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Ingres%2C_Self-portrait.jpg",
    movementLabel: "Troubadour style",
    width: "56",
    height: "47",
    description: "painting by Jean Auguste Dominique Ingres",
    abstract:
      "The Dauphin's Entry Into Paris is an 1821 painting by Jean-Auguste-Dominique Ingres. It is now in the Wadsworth Atheneum collection.\\nIt belongs to the painter's Troubador style period and shows the future Charles V of France returning to Paris on 2 August 1358 after a revolt there. It was commissioned by Amédée-David Pastoret, whose ancestor Jehan Pastoret, president of the parliament of Paris, is shown in red.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/5f/Les_Enfants_d%27%C3%89douard_-_Paul_Delaroche_-_MBA_Lyon_2014.jpg",
    paintingLabel: "The Children of Edward",
    artistName: "Paul Delaroche",
    date_of_birth: "1797",
    date_of_death: "1856",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/ee/Delaroche_autoportrait_fusain_1838.jpg",
    movementLabel: "Troubadour style",
    width: "215",
    height: "181",
    description: "painting by Paul  Delaroche",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/La_convalescence_de_Bayard-Pierre_R%C3%A9voil-MBA_Lyon_2014.jpeg",
    paintingLabel: "La Convalescence de Bayard",
    artistName: "Pierre Révoil",
    date_of_birth: "1776",
    date_of_death: "1842",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/02/Pierre_Revoil-Jean_Michel_Grobon-MBA_Lyon_1982-104-IMG_0459.jpg",
    movementLabel: "Troubadour style",
    width: "177",
    height: "135",
    description: "painting by Pierre Révoil",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/e3/IngresDeathOfDaVinci.jpg",
    paintingLabel: "The Death of Leonardo da Vinci",
    artistName: "Jean Auguste Dominique Ingres",
    date_of_birth: "1780",
    date_of_death: "1867",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Ingres%2C_Self-portrait.jpg",
    movementLabel: "Troubadour style",
    width: "50.5",
    height: "40",
    description: "painting by Jean Auguste Dominique Ingres",
    abstract:
      "The Death of Leonardo da Vinci is an 1818 painting by the French artist Jean Auguste Dominique Ingres, showing the painter Leonardo da Vinci dying, with Francis I of France holding his head. It was commissioned by the Pierre Louis Jean Casimir de Blacas, the French ambassador in Rome, and now hangs in the Petit Palais in Paris.",
  },
] satisfies TroubadourStyle

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default troubadourStyle
