// This file is automatically generated. Do not modify manually.

export type UmbrianSchool = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const umbrianSchool: UmbrianSchool = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/83/Tavolette_di_s._bernardino%2C_1473%2C_san_bernardino_guarisce_una_donna_sterile_o_resuscita_un_bambino_nato_morto.jpg",
    paintingLabel:
      "Saint Bernardino heals a barren woman or resurrects a dead child",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    width: "57",
    height: "75",
    description: "painting by Pietro Perugino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/23/Madonna_dei_Consoli_deruta.jpg",
    paintingLabel: "Madonna with child",
    artistName: "Niccolò di Liberatore",
    date_of_birth: "1430",
    date_of_death: "1502",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/7/7d/Nicolo_alunno_foligno.jpg",
    movementLabel: "Umbrian school",
    width: "144",
    description: "painting by Niccolò Alunno",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Pietro_Perugino_045.jpg",
    paintingLabel: "Saint Bernard",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    width: "57",
    height: "75",
    description: "painting by Pietro Perugino",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/Gonfalone_di_Sant%27Antonio_Abate.jpg",
    paintingLabel: "Saint Anthony",
    artistName: "Niccolò di Liberatore",
    date_of_birth: "1430",
    date_of_death: "1502",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/7/7d/Nicolo_alunno_foligno.jpg",
    movementLabel: "Umbrian school",
    width: "114",
    height: "221",
    description: "painting by Niccolò Alunno",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/e0/Pietro_Perugino_cat03.jpg",
    paintingLabel: "Miracle of the Snow",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    width: "40",
    height: "18.7",
    description: "painting by Pietro Perugino",
    abstract:
      "Miracle of the Snow is a tempera on panel painting by Perugino, dating to around 1472 and now in the collection of Polesden Lacey. It shows the miraculous fall of snow which marked the spot for the foundation of Santa Maria Maggiore in Rome in 352.\\nIt belongs to the painter's early period and the important commissions he gained during the short time he was active in Florence. Both it and Birth of the Virgin Mary are usually identified as one of two surviving parts of the same predella, either from a lost altarpiece of the Virgin Mary or from the Piazza Madonna by Verrocchio's studio. Both predella panels were in the Pucci chapel in Santissima Annunziata in Florence by 1786, when they were bought by John Campbell. They were sold to different owners in London in 1804, with Miracle entering Polesden Lacey collection.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/11/Pietro_Perugino_cat02.jpg",
    paintingLabel: "The Nativity of the Virgin",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    width: "41",
    height: "18.6",
    description: "painting by Pietro Perugino",
    abstract:
      "Nativity of the Virgin is a small tempera on panel painting by Perugino, dating to around 1472 and now in the Walker Art Gallery in Liverpool. It shows the nativity of Mary. The style of the house is heavily influenced by Andrea del Verrocchio\\nIt belongs to the painter's early period and the important commissions he gained during the short time he was active in Florence. Both it and Miracle of the Snow are usually identified as one of two surviving parts of the same predella, either from a lost altarpiece of the Virgin Mary or from the Piazza Madonna by Verocchio's studio. Both panels were in the Pucci chapel in Santissima Annunziata in Florence by 1786, when they were bought by John Campbell. They were sold to different owners in London in 1804, with Birth bought by William Roscoe for nine guineas. At the time of the sale it was misattributed to Masaccio.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/30/Pietro_Perugino_cat07.jpg",
    paintingLabel: "Gonfalon with the Pietà",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    width: "165",
    height: "128",
    description: "painting by Pietro Perugino",
    abstract:
      "The Pietà Gonfalon (Italian - Gonfalone con la Pietà) is a c. 1472 tempera on canvas painting by Pietro Perugino, now in the Galleria Nazionale dell'Umbria in Perugia. It was produced as a gonfalon or processional banner for the Franciscan monastery at Farneto, near Perugia. It is an early work by the artist and shows the Pietà.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3e/Pietro_Perugino_cat05.jpg",
    paintingLabel: "The Visitation",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    width: "34",
    height: "32",
    description: "Pietro Perugino",
    abstract:
      "Visitation is a c.1472 tempera on panel painting usually attributed to Perugino, now in the Galleria dell'Accademia in Florence. An early work by the artist from around the same time as Nativity of the Virgin, whilst he was still heavily influenced by Andrea del Verrocchio, it probably originated as part of the predella for a lost altarpiece. It shows the Visitation, with the Virgin Mary's mother Saint Anne to the left. In the left background is Francis of Assisi receiving the stigmata and in the right background is Florence's patron saint John the Baptist - this may indicate that the lost altarpiece was intended for a Franciscan monastery in Florence such as Santa Croce.\\nThere is debate over the painting's attribution to Perugino - Mackowsky, Raimond Van Marle and Ugo Procacci instead attributed it to Jacopo del Sellaio or his school. The attribution to Perugino was first mooted in 1959 at a conference by Federico Zeri. Anna Padoa Rizzo agrees, but Jean K. Cadogan instead attributes it to Domenico Ghirlandaio.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/Pietro_Perugino_cat06.jpg",
    paintingLabel: "Adoration of the Magi",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    width: "180",
    height: "241",
    description: "painting by the Italian Renaissance painter Pietro Perugino",
    abstract:
      "The Adoration of the Magi  is a painting   by the Italian  Renaissance painter   Pietro Perugino, housed in the Galleria Nazionale dell'Umbria of Perugia, Italy.\\nAccording to Italian art historian Vittoria Garibaldi, it was one of the earliest commissions received by Perugino around the end of his apprenticeship in Florence (1472), while others date it to the late 1470s. The painting was originally executed for the church of Santa Maria dei Servi in Perugia, connected to the Baglioni family; in 1543 it was moved to the church of Santa Maria Nuova in the same city.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6c/Pietro_Perugino_cat10.jpg",
    paintingLabel: "The Eternal Father bless Saints Roch and Romain",
    artistName: "Pietro Perugino",
    date_of_birth: "1448",
    date_of_death: "1523",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3b/Pietro_Perugino_031.jpg",
    movementLabel: "Umbrian school",
    description: "painting by Pietro Perugino",
    abstract:
      "God the Father with Two Saints is a 1477–78 fresco by Perugino. It was painted for the church of San Francesco in Deruta and shows the town at its base, along with the inscription 'DECRETO PUBBLICO DFCTA / ANNO D[OMI]NI MCCCCLXXV[II/III]'. This shows it was an ex voto for the end of the plague in 1476 - the two saints are St Roch (right) and St Romanus (left), both invoked against the plague.It comes from the painter's initial period back in Umbria after returning following his training under Andrea del Verrocchio in Florence. It reuses elements from his previous work  - St Roch's head is similar to that of Balthazar in Adoration of the Magi, whilst the pavement pattern is from The Miracle of the Stillborn Child.",
  },
] satisfies UmbrianSchool

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default umbrianSchool
