// This file is automatically generated. Do not modify manually.

export type YoungPoland = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const youngPoland: YoungPoland = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Mehoffer_Portrait_of_artist%27s_wife.jpg",
    paintingLabel: "Portrait of artist's wife, Jadwiga (nee Janakowska)",
    artistName: "Józef Mehoffer",
    date_of_birth: "1869",
    date_of_death: "1946",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/f/f2/J%C3%B3zef_Mehoffer_by_Wyspia%C5%84ski%2C_1898.jpg",
    movementLabel: "Young Poland",
    width: "51",
    height: "68",
    description: "painting by Józef Mehoffer",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/41/Oku%C5%84_Portrait_of_Mrs_Herse.jpg",
    paintingLabel: "Portrait of Mrs Herse.",
    artistName: "Edward Okuń",
    date_of_birth: "1872",
    date_of_death: "1945",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a1/Edward_Oku%C5%84_-_Autoportret_1911.jpg",
    movementLabel: "Young Poland",
    width: "100",
    height: "135",
    description: "painting by Edward Okuń",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/e0/Oku%C5%84_Wisteria_in_bloom.jpg",
    paintingLabel: "Wisteria in bloom.",
    artistName: "Edward Okuń",
    date_of_birth: "1872",
    date_of_death: "1945",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a1/Edward_Oku%C5%84_-_Autoportret_1911.jpg",
    movementLabel: "Young Poland",
    width: "34",
    height: "44.5",
    description: "painting by Edward Okuń",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/e4/Witold_Wojtkiewicz_-_Dolls_-_Google_Art_Project.jpg",
    paintingLabel: "Dolls by Witold Wojtkiewicz",
    artistName: "Witold Wojtkiewicz",
    date_of_birth: "1879",
    date_of_death: "1909",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/2/29/Witold_Wojtkiewicz_Polish_Painter_photographic_self-portrait.jpg",
    movementLabel: "Young Poland",
    width: "89",
    height: "69",
    description: "painting by Witold Wojtkiewicz",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/78/Mehoffer_Konstanty_Laszczka.jpg",
    paintingLabel: "Portrait of sculptor Konstanty Laszczka.",
    artistName: "Józef Mehoffer",
    date_of_birth: "1869",
    date_of_death: "1946",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/f/f2/J%C3%B3zef_Mehoffer_by_Wyspia%C5%84ski%2C_1898.jpg",
    movementLabel: "Young Poland",
    width: "97.2",
    height: "146.5",
    description: "painting by Józef Mehoffer",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c2/Jacek_Malczewski%2C_Hamlet_Polski_-_Portret_Aleksandra_Wielopolskiego.jpg",
    paintingLabel: "Polish Hamlet. Portrait of Aleksander Wielopolski",
    artistName: "Jacek Malczewski",
    date_of_birth: "1854",
    date_of_death: "1929",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/9/96/Malczewski_Jacek_Autoportret1907.jpg",
    movementLabel: "Young Poland",
    width: "149",
    height: "100",
    description: "painting by Jacek Malczewski",
    abstract:
      "Polish Hamlet. Portrait of Alexander Wielopolski is an oil painting by Jacek Malczewski from 1903, presenting the allegorical grandson Alexander Wielopolski and two different visions of the fate of the Polish nation.",
  },
] satisfies YoungPoland

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default youngPoland
