import type { Metadata } from "next"
import { Inter } from "next/font/google"
import classNames from "../../node_modules/classnames/index"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Master or Machine",
  description: "Guess which image was generated by AI.",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={classNames(
          "m-0 px-4 h-screen w-screen dark:bg-darkBg",
          inter.className,
        )}
      >
        {children}
      </body>
    </html>
  )
}
