// This file is automatically generated. Do not modify manually.

export type AnalyticalCubism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const analyticalCubism: AnalyticalCubism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/61/Head_of_a_Peasant_Girl.jpg",
    paintingLabel: "Head of a Peasant Girl",
    artistName: "Kazimir Malevich",
    date_of_birth: "1878",
    date_of_death: "1935",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/6/63/Casimir_Malevich_photo.jpg",
    movementLabel: "analytical cubism",
    description: "paintings by Kazimir Malevich",
  },
] satisfies AnalyticalCubism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default analyticalCubism
