// This file is automatically generated. Do not modify manually.

export type ArtDeco = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const artDeco: ArtDeco = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/58/Amedeo_Modigliani_028.jpg",
    paintingLabel: "Ritratto di Lunia Czechowska con ventaglio",
    artistName: "Amedeo Modigliani",
    date_of_birth: "1884",
    date_of_death: "1920",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/07/Amedeo-modigliani-identification-photo-nice-1918.jpg",
    movementLabel: "Art Deco",
    width: "65",
    height: "100",
    description: "painting by Amedeo Modigliani",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/73/The_Worker_and_Kolkhoz_Woman.jpg",
    paintingLabel: "Worker and Kolkhoz Woman",
    artistName: "Vera Ignatyevna Mukhina",
    date_of_birth: "1889",
    date_of_death: "1953",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/5/5e/1989_CPA_6077.jpg",
    movementLabel: "Art Deco",
    height: "24.5",
    description: "monumental sculpture",
    abstract:
      "Worker and Kolkhoz Woman (Russian: Рабо́чий и колхо́зница, tr. Rabóchy i kolkhóznitsa) is a sculpture of two figures with a sickle and a hammer raised over their heads. It is 24.5 meters (78 feet) high, made from stainless steel by Vera Mukhina for the 1937 World's Fair in Paris, and subsequently moved to Moscow. The sculpture is an example of socialist realism in an Art Deco aesthetic. The worker holds aloft a hammer and the kolkhoz woman a sickle to form the hammer and sickle symbol.\\n\\n",
  },
] satisfies ArtDeco

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default artDeco
