// This file is automatically generated. Do not modify manually.

export type ArtisticIndianism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const artisticIndianism: ArtisticIndianism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/56/Victor_Meirelles_-_Moema.jpg",
    paintingLabel: "Moema",
    artistName: "Victor Meirelles",
    date_of_birth: "1832",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/14/RETRATO_DE_VICTOR_MEIRELLES_-_A._Pelliciari_-_1915.jpg",
    movementLabel: "artistic indianism",
    width: "190",
    height: "129",
    description: "painting by Victor Meirelles",
    abstract:
      "Moema is an oil painting created in 1886 by Brazilian artist Victor Meirelles. It depicts the homonym character from the epic poem Caramuru (1781), by Santa Rita Durão. The work does not depict a scene from the poem, but instead Meirelles's personal interpretation of the character's fate, submerging into the water after being rejected by Caramuru.The painting was shown for the first time in 1866, in the Imperial Academy of Fine Arts. It is a part of the collection of the São Paulo Museum of Art since 1947. Under Beatriz Pimenta Camargo's presidency, the museum has obtained funds for the restoration of the painting, considered to be one of the most important in its collection.A preparatory sketch created before the actual painting shows Moema in a different position, as well as a group of natives in the background which are more prominent than the group in the finished painting's background.",
  },
] satisfies ArtisticIndianism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default artisticIndianism
