// This file is automatically generated. Do not modify manually.

export type Bauhaus = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const bauhaus: Bauhaus = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/Konzentrische_Gruppe_-_Oskar_Schlemmer.jpg",
    paintingLabel: "Concentric Group",
    artistName: "Oskar Schlemmer",
    date_of_birth: "1888",
    date_of_death: "1943",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/07/Oskar_Schlemmer_by_Hugo_Erfurth%2C_1920.jpg",
    movementLabel: "Bauhaus",
    width: "62",
    height: "97.5",
    description: "painting by Oskar Schlemmer",
    abstract: "Concentric Group is a painting by Oskar Schlemmer, from 1925.",
  },
] satisfies Bauhaus

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default bauhaus
