// This file is automatically generated. Do not modify manually.

export type ConcreteArt = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const concreteArt: ConcreteArt = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/84/Hh-alsterpark8_Max_Bill.jpg",
    paintingLabel: "Rhythmus im Raum",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Hamburg, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c7/Marl_Bill_01.JPG",
    paintingLabel: "Säule mit 3-6-eckigen Querschnitten",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Marl, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/bb/FFM_Sculpture_Kontinuitaet_2012_Max_Bill_1986_1.jpg",
    paintingLabel: "Kontinuität",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Frankfurt, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1e/Leverkusen_-_Schloss_Morsbroich_03_ies.jpg",
    paintingLabel: "Säule mit drei- bis achteckigem Querschnitt",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Leverkusen, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/66/Wedding_Kurt-Schumacher-Damm_Berlin_dankt_Frankreich.jpg",
    paintingLabel: "Berlin dankt Frankreich",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Berlin, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d0/%D0%A3%D0%BB%D1%8C%D0%BC._%D0%9F%D0%B0%D0%BC%D1%8F%D1%82%D0%BD%D0%B8%D0%BA_%D0%AD%D0%B9%D0%BD%D1%88%D1%82%D0%B5%D0%B9%D0%BD%D1%83.jpg",
    paintingLabel: "Monument für Albert Einstein",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Ulm, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b2/Max_Bill_unendliche_Schleife_7890.JPG",
    paintingLabel: "Unendliche Schleife",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Essen, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/70/Pavillon-Skulptur_Max_Bill_01.jpg",
    paintingLabel: "Pavillon-Skulptur",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Zürich, Switzerland",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/e4/Familie_von_fuenf_halben_Kugeln_1_a_retouched.jpg",
    paintingLabel: "Familie von fünf halben Kugeln",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "set of five sculptures by Max Bill",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/e6/Bottrop_Bill_01.JPG",
    paintingLabel: "Einheit aus drei gleichen Volumen",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    height: "232",
    description: "sculpture by Max Bill",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/51/Ulm_Bill_088.jpg",
    paintingLabel: "Drei Bildsäulen",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill in Ulm, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b7/Max_Bill_o.T._1978-83_Klinikum_Gro%C3%9Fhadern_Muenchen-5.jpg",
    paintingLabel: "Bildsäule",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    height: "16",
    description: "sculpture by Max Bill in Munich, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/43/Max_Bill_Rhythmus_im_Raum_1994_EP_Muenchen-13.jpg",
    paintingLabel: "Rhythmus im Raum",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    width: "10.65",
    height: "3.20",
    description: "sculpture by Max Bill in Munich, Germany",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/11/Endlose_Treppe_in_Ludwigshafen_02.jpg",
    paintingLabel: "Endlose Treppe (Monument für Ernst Bloch)",
    artistName: "Max Bill",
    date_of_birth: "1908",
    date_of_death: "1994",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/04/Com_L19-0188-0203A.jpg",
    movementLabel: "concrete art",
    description: "sculpture by Max Bill",
    abstract:
      "The Endlose Treppe (meaning 'Endless Steps' in German) is a sculpture made by the Swiss artist Max Bill in 1991 for the philosopher Ernst Bloch. It is made of North American granite. \\nIt stands near the Wilhelm-Hack-Museum in the city-center of Ludwigshafen am Rhein. According to the artist, the 19 winding steps of granite, which stand nearly 10 meters, are supposed to represent Ernst Bloch's 'principle of hope'.",
  },
] satisfies ConcreteArt

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default concreteArt
