// This file is automatically generated. Do not modify manually.

export type Costumbrismo = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const costumbrismo: Costumbrismo = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/53/Retrato_de_do%C3%B1a_Serapia_Mu%C3%B1oz_by_Rafael_Romero_Barros.jpg",
    paintingLabel: "Portrait of lady Serapia Muñoz",
    artistName: "Rafael Romero Barros",
    date_of_birth: "1832",
    date_of_death: "1895",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1f/Retrato_de_Rafael_Romero_Barros_by_Tom%C3%A1s_Mu%C3%B1oz_Lucena.jpg",
    movementLabel: "Costumbrismo",
    width: "75",
    height: "101",
    description: "painting by Rafael Romero Barros",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6a/Retrato_de_Jos%C3%A9_S%C3%A1nchez_Pe%C3%B1a_by_Rafael_Romero_de_Barros.jpg",
    paintingLabel: "Portrait of José Sánchez Peña",
    artistName: "Rafael Romero Barros",
    date_of_birth: "1832",
    date_of_death: "1895",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1f/Retrato_de_Rafael_Romero_Barros_by_Tom%C3%A1s_Mu%C3%B1oz_Lucena.jpg",
    movementLabel: "Costumbrismo",
    width: "100",
    height: "81",
    description: "painting by Rafael Romero Barros",
  },
] satisfies Costumbrismo

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default costumbrismo
