// This file is automatically generated. Do not modify manually.

export type DanishGoldenAge = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const danishGoldenAge: DanishGoldenAge = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/76/Eckersberg%2C_CW_-_Udsigt_til_en_g%C3%A5rd_i_Rom.jpg",
    paintingLabel: "Interior of a yard in Rome",
    artistName: "Christoffer Wilhelm Eckersberg",
    date_of_birth: "1783",
    date_of_death: "1853",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/Self_portrait%2C_by_Christoffer_Wilhelm_Eckersberg.jpg",
    movementLabel: "Danish Golden Age",
    width: "27.5",
    height: "34",
    description: "painting by Eckersberg",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/Christen_K%C3%B8bke_-_The_North_Gate_of_the_Citadel_-_Google_Art_Project.jpg",
    paintingLabel: "The North Gate of the Citadel",
    artistName: "Christen Købke",
    date_of_birth: "1810",
    date_of_death: "1848",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/13/Selvportr%C3%A6t_%28ca._1833_by_Christen_K%C3%B8bke%29.jpg",
    movementLabel: "Danish Golden Age",
    width: "93",
    height: "79",
    description: "painting by Christen Købke",
  },
] satisfies DanishGoldenAge

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default danishGoldenAge
