// This file is automatically generated. Do not modify manually.

export type DieBrCke = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const dieBrCke: DieBrCke = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Ernst-Ludwig-Kirchner-Weiblicher-Akt-mit-Hut-Museum-Ludwig.jpg",
    paintingLabel: "Half-Length Nude with Hat",
    artistName: "Ernst Ludwig Kirchner",
    date_of_birth: "1880",
    date_of_death: "1938",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    movementLabel: "Die Brücke",
    description: "painting by Ernst Ludwig Kirchner",
  },
] satisfies DieBrCke

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default dieBrCke
