// This file is automatically generated. Do not modify manually.

export type ExperimentalArchitecture = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const experimentalArchitecture: ExperimentalArchitecture = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d6/Rotterdam_Woods_01.JPG",
    paintingLabel: "Hermitage",
    artistName: "Lebbeus Woods",
    date_of_birth: "1940",
    date_of_death: "2012",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/c/c2/Lebbeus_Woods.jpg",
    movementLabel: "experimental architecture",
    description:
      "public artwork by Lebbeus Woods in Rotterdam, the Netherlands",
  },
] satisfies ExperimentalArchitecture

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default experimentalArchitecture
