// This file is automatically generated. Do not modify manually.

export type Expressionism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const expressionism: Expressionism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/f8/Marc-little_blue_horses.jpg",
    paintingLabel: "The Little Blue Horses",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b2/At_the_Mirror_by_Lovis_Corinth%2C_1912_-_Worcester_Art_Museum_-_IMG_7146.JPG",
    paintingLabel: "At the Mirror by Lovis Corinth",
    artistName: "Lovis Corinth",
    date_of_birth: "1858",
    date_of_death: "1925",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/7/78/Lovis_Corinth_Selbstportr%C3%A4t_ohne_Kragen.jpg",
    movementLabel: "expressionism",
    description: "painting by Lovis Corinth",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/bd/Paul_Klee_-_Ad_Parnassum.jpg",
    paintingLabel: "Ad Parnassum",
    artistName: "Paul Klee",
    date_of_birth: "1879",
    date_of_death: "1940",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/6/6e/Paul_Klee_1911.jpg",
    movementLabel: "expressionism",
    width: "126",
    height: "100",
    description: "painting by Paul Klee",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/68/1911_Marc_Liegender_Hund_im_Schnee_anagoria.JPG",
    paintingLabel: "Dog Lying in the snow",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "105",
    height: "62.5",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b8/Firma_de_Guillermo_Silveira_1984.jpg",
    paintingLabel: "Men and machines",
    artistName: "Guillermo Silveira García",
    date_of_birth: "1922",
    date_of_death: "1987",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/5/5e/Retrato_de_Guillermo_Silveira.jpg",
    movementLabel: "expressionism",
    width: "89",
    height: "160",
    description: "painting by Guillermo Silveira García",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/ee/Edvard_Munch_-_Summer_Night_in_Studenterlunden_%281899%29.jpg",
    paintingLabel: "Summer Night in Studenterlunden",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    description: "painting by Edvard Munch (1899)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/7a/Death_and_Fire.JPG",
    paintingLabel: "Death and Fire",
    artistName: "Paul Klee",
    date_of_birth: "1879",
    date_of_death: "1940",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/6/6e/Paul_Klee_1911.jpg",
    movementLabel: "expressionism",
    description: "painting by Paul Klee",
    abstract:
      "Death and Fire, known in German as Tod und Feuer, is a 1940 expressionist painting by Paul Klee. It was one of the last before his death in June 29 of that year. In 1935 Klee started to suffer from scleroderma, which manifested itself with fatigue, skin rashes, difficulty in swallowing, shortness of breath and pain in the joints of his hands. Paintings during this period tended to be simpler and representative of the suffering he was going through. 'Tod', the German word for death, is a common motif throughout the painting. It can be seen most distinctly in the features of the face, though the 'd' and 't' are rotated. The word can also be seen in the figure's raised arm as the 'T', the yellow orb as the 'O', and the figure's head as the 'D'.\\nThe painting also represents hieroglyphics, an interest of Klee's during this time, which can also be seen in many of his other late 1930s paintings, such as Insula dulcamara (1938) and Heroische Rosen (1938). As of 2014, it is on display at Zentrum Paul Klee, a museum in Bern, Switzerland that is dedicated to the works of Paul Klee.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d7/Edvard_Munch_-_Study_of_a_Model_%2870.1926%29.jpg",
    paintingLabel: "Sketch of the Model Posing",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "55.5",
    height: "76.5",
    description: "artwork by Edvard Munch",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/27/Marc-Im_Regen_PA291058.jpg",
    paintingLabel: "In the rain",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "106",
    height: "81.5",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/29/Marc_Reh_im_Walde_II_PA291073.jpg",
    paintingLabel: "Deer in the woods II",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "81",
    height: "110",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/01/Egon_Schiele_-_Tod_und_M%C3%A4dchen_-_3171_-_%C3%96sterreichische_Galerie_Belvedere.jpg",
    paintingLabel: "Death and Maiden",
    artistName: "Egon Schiele",
    date_of_birth: "1890",
    date_of_death: "1918",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/14/Egon_Schiele_photo.jpg",
    movementLabel: "expressionism",
    width: "180",
    height: "150",
    description: "painting by Egon Schiele",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Franz_Marc_-_Weidende_Pferde_I_-_G_12576_-_Lenbachhaus.jpg",
    paintingLabel: "Grazing Horses I",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "94",
    height: "64",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/08/Marc-V%C3%B6gel_PA291069.jpg",
    paintingLabel: "Birds",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "100",
    height: "109",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/ec/Marc-red_and_blue_horses.jpg",
    paintingLabel: "Red and Blue Horses",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "34",
    height: "26.5",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/7f/Franz_Marc_029a.jpg",
    paintingLabel: "The Tower of Blue Horses",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "130",
    height: "200",
    description: "painting by Franz Marc",
    abstract:
      "The Tower of Blue Horses (German: Der Turm der blauen Pferde) is a 1913 oil painting by the German Expressionist artist Franz Marc. It has been called one of his best works, but went missing in 1945.",
  },
  {
    image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Fortvivlan.jpg",
    paintingLabel: "Sick Mood at Sunset. Despair",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    description: "painting by Edvard Munch",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/af/Edvard_Munch_-_Ashes_%281895%29.jpg",
    paintingLabel: "Ashes",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "141",
    height: "120.5",
    description: "painting by Edvard Munch (1894)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/09/Edvard_Munch_-_Death_and_the_Child_%281899%29%2C_Kunsthalle_Bremen.jpg",
    paintingLabel: "Death and the Child",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "90",
    height: "100",
    description: "painting by Edvard Munch (1899 - 1)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0f/VMFA_2009-261a_v1_KW_x-1024x895.jpg",
    paintingLabel: "Bathers (Virginia Museum of Fine Arts, 2009.261)",
    artistName: "Max Pechstein",
    date_of_birth: "1881",
    date_of_death: "1955",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/d4/Fotothek_df_pk_0000220_029_Portr%C3%A4ts%2C_Max_Pechstein_%28cropped%29.jpg",
    movementLabel: "expressionism",
    width: "80.65",
    height: "70.49",
    description: "painting by Max Pechstein",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/af/Franz_Marc_-_Akt_mit_Katze_-_G_12762_-_Lenbachhaus.jpg",
    paintingLabel: "nude with Cat",
    artistName: "Franz Marc",
    date_of_birth: "1880",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    movementLabel: "expressionism",
    width: "82",
    height: "88",
    description: "Franz Marc painting",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/60/Ernst_Ludwig_Kirchner%2C_1913%2C_Street%2C_Berlin%2C_oil_on_canvas%2C_120.6_x_91.1_cm%2C_MoMA.jpg",
    paintingLabel: "Street Berlin",
    artistName: "Ernst Ludwig Kirchner",
    date_of_birth: "1880",
    date_of_death: "1938",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    movementLabel: "expressionism",
    width: "91.1",
    height: "120.6",
    description: "painting by Ernst Ludwig Kirchner",
    abstract:
      "Street, Berlin is an oil painting by Ernst Ludwig Kirchner painted in 1913 before the outbreak of World War 1. At this time, Kirchner painted several different street scenes that illustrated the chaos of city life and the relationship between men and women.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d0/Egon_Schiele_069.jpg",
    paintingLabel: "Portrait of Wally",
    artistName: "Egon Schiele",
    date_of_birth: "1890",
    date_of_death: "1918",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/14/Egon_Schiele_photo.jpg",
    movementLabel: "expressionism",
    width: "39.8",
    height: "32.7",
    description: "painting by Egon Schiele",
    abstract:
      "Portrait of Wally is a 1912 oil painting by Austrian painter Egon Schiele of Walburga 'Wally' Neuzil, a woman whom he met in 1911 when he was 21 and she was 17. She became his lover and model for several years, depicted in a number of Schiele's most striking paintings. The painting was obtained by Rudolf Leopold in 1954 and became part of the collection of the Leopold Museum when it was established by the Austrian government, purchasing 5,000 pieces that Leopold had owned. Near the end of a 1997–1998 exhibit of Schiele's work at the Museum of Modern Art in New York, the painting's ownership (provenance) history was revealed in an article published in The New York Times. After the publication, the heirs of Lea Bondi Jaray, to whom the work had belonged before World War II, contacted the New York County District Attorney who issued a subpoena forbidding its return to Austria. The work was tied up in litigation for years by Bondi's heirs, who claimed that the painting was Nazi plunder and should have been returned to them.\\nIn July 2010, the Leopold Museum agreed to pay $19 million to Bondi's heirs under an agreement that would address all outstanding claims on the painting.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/ef/Edvard_Munch_-_The_Kiss_-_Google_Art_Project.jpg",
    paintingLabel: "The Kiss",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "81",
    height: "99",
    description: "painting by Edvard Munch (1897 - 1)",
    abstract:
      "The Kiss is an oil painting on canvas completed by the Norwegian symbolist artist Edvard Munch in 1897. Part of his Frieze of Life, which depicts the stages of a relationship between men and women, The Kiss is a realization of a motif with which he had experimented since 1888/89: a couple kissing, their faces fusing as one in a symbolic representation of their unity. Exhibited as early as 1903, this work is held at the Munch Museum in Oslo.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b6/Edvard_Munch_-_The_dance_of_life_%281899-1900%29.jpg",
    paintingLabel: "Dance of Life",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "191",
    height: "129",
    description: "painting by Edvard Munch (1899–1900)",
    abstract:
      "The Dance of Life or Life's Dance is an 1899–1900 expressionist painting by Edvard Munch, now in the National Museum of Art in Norway.The painting was an important work in Munch's project The Frieze of Life. In creating the painting, Munch was allegedly inspired by the Helge Rode play Dansen gaar, of which Munch kept a copy in his personal library.Olaf Schou purchased the painting in Oslo in 1910, immediately presenting it to the National Gallery.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c6/Edvard_Munch_-_Vampire_%281893%29%2C_Munchmuseet.jpg",
    paintingLabel: "Vampire",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "98",
    height: "77",
    description: "painting by Edvard Munch (1893 - 2)",
    abstract:
      "Love and Pain is a painting by Edvard Munch, It has also been called Vampire, though not by Munch. Munch painted six different versions of the subject in the period 1893–1895; three versions are at the Munch Museum in Oslo, one is at the Gothenburg Museum of Art, one is owned by a private collector and the last one is unaccounted for. He also painted several versions and derivatives in his later career.The painting shows a woman with long flame-red hair kissing a man on the neck, as the couple embrace. Although others have seen in it 'a man locked in a vampire's tortured embrace – her molten-red hair running along his soft bare skin,' Munch himself always claimed it showed nothing more than 'just a woman kissing a man on the neck'.The painting was first called Vampire by Munch's friend, the critic Stanisław Przybyszewski. Przybyszewski saw the painting on exhibition and described it as 'a man who has become submissive, and on his neck a biting vampire's face.'A version of the painting was stolen from the Munch Museum on 23 February 1988. It was recovered later the same year, when the thief contacted the police.\\nIn 2008, at a Sotheby's auction, an 1894 version of the painting sold for 38.2 million dollars (24.3 million pounds) and set the world record for the auction of a Munch painting.\\n\\nIn 1895, Munch created a woodcut with a very similar theme and composition, known as Vampyr II.\\n\\nIn 1916–1918, Munch reused the composition in a different setting for two paintings called Vampire in the Forest and Vampire, currently in the collection of the Munch Museum.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d0/Londres_tate_modern_kirchner_baigneurs.jpg",
    paintingLabel: "Bathers at Moritzburg",
    artistName: "Ernst Ludwig Kirchner",
    date_of_birth: "1880",
    date_of_death: "1938",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    movementLabel: "expressionism",
    width: "199.7",
    height: "151.1",
    description: "painting by Ernst Ludwig Kirchner",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/ae/Edvard_Munch_-_Anxiety_-_Google_Art_Project.jpg",
    paintingLabel: "Anxiety",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "74",
    height: "94",
    description: "painting by Edvard Munch",
    abstract:
      "Anxiety (Norwegian: Angst) is an oil-on-canvas painting created by the expressionist artist Edvard Munch in 1894. It's currently housed in Munch Museum in Oslo, Norway. Many art critics feel that Anxiety is closely related to Munch’s more famous piece, The Scream (1893). The faces show despair and the dark colors show a depressed state. Many critics also believe it’s meant to show the emotions of heartbreak and sorrow.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Edvard_Munch%2C_Hjemvendende_arbejdere%2C_1914%2C_KMS3823%2C_SMK.jpg",
    paintingLabel: "Workers on their Way Home",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "160.8",
    height: "130.7",
    description: "painting by Edvard Munch (1914)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/Girl_in_the_shirt_%28Red-haired_girl%29_by_Amedeo_Modigliani.jpg",
    paintingLabel: "Girl in the shirt (Red-haired girl)",
    artistName: "Amedeo Modigliani",
    date_of_birth: "1884",
    date_of_death: "1920",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/07/Amedeo-modigliani-identification-photo-nice-1918.jpg",
    movementLabel: "expressionism",
    width: "50",
    height: "73",
    description: "painting by Amedeo Modigliani",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Ernst-Ludwig-Kirchner-Weiblicher-Akt-mit-Hut-Museum-Ludwig.jpg",
    paintingLabel: "Half-Length Nude with Hat",
    artistName: "Ernst Ludwig Kirchner",
    date_of_birth: "1880",
    date_of_death: "1938",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    movementLabel: "expressionism",
    description: "painting by Ernst Ludwig Kirchner",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b4/Gerstl_-_Die_Familie_Sch%C3%B6nberg.jpg",
    paintingLabel: "Schönberg family",
    artistName: "Richard Gerstl",
    date_of_birth: "1883",
    date_of_death: "1908",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/Gerstl_-_Selbstbildnis.jpg",
    movementLabel: "expressionism",
    width: "88.80",
    height: "109.70",
    description: "painting by Richard Gerstl",
    abstract:
      "Schönberg Family is a painting by Richard Gerstl, from 1907.\\n\\n",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/8f/The_White_Apple_Tree%2C_Antanas_Samuolis.jpg",
    paintingLabel: "The White Apple Tree",
    artistName: "Antanas Samuolis",
    date_of_birth: "1899",
    date_of_death: "1942",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/2/2a/Selfportrait_antanas_samuolis.jpg",
    movementLabel: "expressionism",
    width: "71",
    height: "89",
    description: "painting by Antanas Samuolis",
    abstract:
      "White Apple Tree (Lithuanian: Baltoji obelis) is a 1932 painting by the Lithuanian artist Antanas Samuolis.\\n\\n",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0f/Munch_Moonlight.jpg",
    paintingLabel: "Moonlight",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "110",
    height: "93",
    description: "painting by Edvard Munch (1895)",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b8/Kirchner_1909_Marzella.jpg",
    paintingLabel: "Marzella",
    artistName: "Ernst Ludwig Kirchner",
    date_of_birth: "1880",
    date_of_death: "1938",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    movementLabel: "expressionism",
    width: "60",
    height: "76",
    description: "painting by Ernst Ludwig Kirchner",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d5/Kirchner_-_F%C3%BCnf_badende_am_See.jpg",
    paintingLabel: "Five Bathing Women at a Lake",
    artistName: "Ernst Ludwig Kirchner",
    date_of_birth: "1880",
    date_of_death: "1938",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    movementLabel: "expressionism",
    description: "painting by Ernst Ludwig Kirchner",
    abstract:
      "Five Bathing at a Lake (German: Fünf badende am See) is an 1911 oil on canvas painting by the Expressionist German painter Ernst Ludwig Kirchner. The painting is exhibited at Brucke Museum in Berlin.",
  },
] satisfies Expressionism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default expressionism
