// This file is automatically generated. Do not modify manually.

export type Fauvism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const fauvism: Fauvism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/8b/View_of_Agay_Albert_Marquet_%281905%29.jpg",
    paintingLabel: "Paysage, baie méditerranéenne, vue d'Agay",
    artistName: "Albert Marquet",
    date_of_birth: "1875",
    date_of_death: "1947",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/84/Albert_Marquet_%281875-1947%29%2C_c._1920s.jpg",
    movementLabel: "fauvism",
    width: "80.7",
    height: "64.5",
    description: "painting by Albert Marquet",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b1/The_Beach_at_F%C3%A9camp_Albert_Marquet_%281906%29.jpg",
    paintingLabel: "La plage de Fécamp",
    artistName: "Albert Marquet",
    date_of_birth: "1875",
    date_of_death: "1947",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/84/Albert_Marquet_%281875-1947%29%2C_c._1920s.jpg",
    movementLabel: "fauvism",
    width: "60.8",
    height: "50",
    description: "painting by Albert Marquet",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/de/July-14th-at-havre-1906.jpg%21PinterestLarge.jpg",
    paintingLabel: "14 July at Le Havre",
    artistName: "Albert Marquet",
    date_of_birth: "1875",
    date_of_death: "1947",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/84/Albert_Marquet_%281875-1947%29%2C_c._1920s.jpg",
    movementLabel: "fauvism",
    width: "65",
    height: "81",
    description: "painting by Albert Marquet",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/5d/Matisse_in_Manguin%27s_Studio_Albert_Marquet_%281905%29.jpg",
    paintingLabel: "Matisse in Manguin's Studio",
    artistName: "Albert Marquet",
    date_of_birth: "1875",
    date_of_death: "1947",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/8/84/Albert_Marquet_%281875-1947%29%2C_c._1920s.jpg",
    movementLabel: "fauvism",
    width: "73",
    height: "100",
    description: "painting by Albert Marquet",
  },
] satisfies Fauvism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default fauvism
