// This file is automatically generated. Do not modify manually.

export type FrenchRenaissance = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const frenchRenaissance: FrenchRenaissance = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/13/Charles_IX_-_Workshop_of_Fran%C3%A7ois_Clouet.jpg",
    paintingLabel: "Charles IX",
    artistName: "François Clouet",
    date_of_birth: "1510",
    date_of_death: "1572",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/3a/Francois-Clouet.jpg",
    movementLabel: "French Renaissance",
    width: "22.9",
    height: "30.5",
    description: "painting by Francois Clouet",
  },
] satisfies FrenchRenaissance

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default frenchRenaissance
