// This file is automatically generated. Do not modify manually.

export type FrenchPaintingInThe18thCentury = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const frenchPaintingInThe18thCentury: FrenchPaintingInThe18thCentury = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/dc/Charles_de_La_Fosse_-_The_Finding_of_Moses_-_WGA12309.jpg",
    paintingLabel: "Moses saved from the waters",
    artistName: "Charles de La Fosse",
    date_of_birth: "1636",
    date_of_death: "1716",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/b5/1691_-_Charles_de_La_Fosse_%28gr._Duchange%29.jpg",
    movementLabel: "French painting in the 18th century",
    width: "110",
    height: "125",
    description: "painting by Charles de la Fosse",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/4/46/BoucherFrancois_Europe.jpg",
    paintingLabel: "The Rape of Europa or Abduction of Europa",
    artistName: "François Boucher",
    date_of_birth: "1703",
    date_of_death: "1770",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/f/f9/Boucher_par_Gustav_Lundberg_1741.jpg",
    movementLabel: "French painting in the 18th century",
    width: "193.5",
    height: "160.5",
    description: "painting by François Boucher",
  },
] satisfies FrenchPaintingInThe18thCentury

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default frenchPaintingInThe18thCentury
