// This file is automatically generated. Do not modify manually.

export type GermanRomanticism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const germanRomanticism: GermanRomanticism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
    paintingLabel: "Wanderer above the Sea of Fog",
    artistName: "Caspar David Friedrich",
    date_of_birth: "1774",
    date_of_death: "1840",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/c/cd/%D0%9A%D0%B0%D1%81%D0%BF%D0%B0%D1%80_%D0%94%D0%B0%D0%B2%D0%B8%D0%B4_%D0%A4%D1%80%D0%B8%D0%B4%D1%80%D0%B8%D1%85.%D0%9F%D0%BE%D0%B7%D0%B4%D0%BD%D0%B8%D0%B9_%D0%B0%D0%B2%D1%82%D0%BE%D0%BF%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82.jpg",
    movementLabel: "German Romanticism",
    width: "74.8",
    height: "94.8",
    description: "oil painting by Caspar David Friedrich",
    abstract:
      "Wanderer above the Sea of Fog (German: Der Wanderer über dem Nebelmeer), also known as Wanderer above the Mist or Mountaineer in a Misty Landscape, is an oil painting c. 1818 by the German Romantic artist Caspar David Friedrich. It has been considered one of the masterpieces of Romanticism and one of its most representative works. It currently resides in the Kunsthalle Hamburg in Hamburg, Germany.",
  },
] satisfies GermanRomanticism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default germanRomanticism
