// This file is automatically generated. Do not modify manually.

export type HellenisticSculpture = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const hellenisticSculpture: HellenisticSculpture = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/9c/MG-Paris-Aphrodite_of_Milos.jpg",
    paintingLabel: "Venus de Milo",
    artistName: "Alexandros of Antioch",
    date_of_birth: "-200",
    date_of_death: "-100",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/9/9c/MG-Paris-Aphrodite_of_Milos.jpg",
    movementLabel: "Hellenistic sculpture",
    height: "202",
    description: "Greek marble statue of a woman, famously without arms",
    abstract:
      "The Venus de Milo (Greek: Αφροδίτη της Μήλου, Aphroditi tis Milou) is an ancient Greek statue and one of the most famous works of ancient Greek sculpture. Initially it was attributed to the sculptor Praxiteles, but based on an inscription that was on its plinth, the statue is now thought to be the work of Alexandros of Antioch.Created sometime between 130 and 100 BC, the statue is believed to depict Aphrodite, the Greek goddess of love and beauty. However, some scholars claim it is the sea-goddess Amphitrite, venerated on Milos. It is a marble sculpture, slightly larger than life size at 203 cm (6 ft 8 in) high. Part of an arm and the original plinth were lost following the statue's discovery. It is currently on permanent display at the Louvre Museum in Paris. The statue is named after Aphrodite's Roman name, Venus, and the Greek island of Milos, where it was discovered.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/65/Venice_-_St._Marc%27s_Basilica_10.jpg",
    paintingLabel: "Horses of Saint Mark",
    artistName: "Lysippos",
    date_of_birth: "-390",
    date_of_death: "-300",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/eb/Cupido4b.jpg",
    movementLabel: "Hellenistic sculpture",
    height: "238",
    description: "sculpture by Lysippos",
    abstract:
      "The Horses of Saint Mark (Italian: Cavalli di San Marco), also known as the Triumphal Quadriga, is a set of Roman bronze statues of four horses, originally part of a monument depicting a quadriga (a four-horse carriage used for chariot racing). The horses were placed on the facade, on the loggia above the porch, of St Mark's Basilica in Venice, northern Italy after the sack of Constantinople in 1204. They remained there until looted by Napoleon in 1797 but were returned in 1815. The sculptures have been removed from the facade and placed in the interior of St Mark's for conservation purposes, with replicas in their position on the loggia.",
  },
] satisfies HellenisticSculpture

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default hellenisticSculpture
