// This file is automatically generated. Do not modify manually.

export type Naturalismo = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const naturalismo: Naturalismo = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/53/Albert_Edelfelt_-_The_Luxembourg_Gardens%2C_Paris.jpg",
    paintingLabel: "The Luxembourg Gardens, Paris",
    artistName: "Albert Edelfelt",
    date_of_birth: "1854",
    date_of_death: "1905",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/47/Albert_Edelfelt-Sj%C3%A4lvportr%C3%A4tt.jpg",
    movementLabel: "Naturalismo",
    width: "186.50",
    height: "141.50",
    description: "painting by Albert Edelfelt",
    abstract:
      "Luxembourg Gardens, Paris is an oil painting by Albert Edelfelt completed in 1887 of a scene in the Jardin du Luxembourg in Paris, France. The painting has become a kind of symbol of Edelfelt and the whole of Finnish art, at a time when Paris was the center of the whole art world. The work is also a larger Edelfelt  paintings and a major en plein air painting.",
  },
] satisfies Naturalismo

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default naturalismo
