// This file is automatically generated. Do not modify manually.

export type Neoclassicalism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const neoclassicalism: Neoclassicalism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6f/Antonio_Canova_%281757-1822%29_-_The_Three_Graces%2C_Woburn_Abbey_version_%281814-1817%29_front_wide_view%2C_Victoria_and_Albert_Museum%2C_April_2013_%2811059679673%29.png",
    paintingLabel: "The Three Graces",
    artistName: "Antonio Canova",
    date_of_birth: "1757",
    date_of_death: "1822",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/6/6b/Antonio_Canova_Selfportrait_1792.jpg",
    movementLabel: "Neoclassicalism",
    description: "statues by Antonio Canova",
  },
] satisfies Neoclassicalism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default neoclassicalism
