// This file is automatically generated. Do not modify manually.

export type NeoGrec = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const neoGrec: NeoGrec = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1e/Jean-L%C3%A9on_G%C3%A9r%C3%B4me_-_Young_Greeks_Attending_a_Cock_Fight_-_Google_Art_Project.jpg",
    paintingLabel: "Young Greeks Attending a Cock Fight",
    artistName: "Jean-Léon Gérôme",
    date_of_birth: "1824",
    date_of_death: "1904",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/5/5c/Jean-Leon_Gerome.jpg",
    movementLabel: "Neo-Grec",
    width: "204",
    height: "143",
    description: "painting by Jean-Léon Gérôme",
    abstract:
      "The Cock Fight (French: Un combat de coqs) is an 1846 painting by the French artist Jean-Léon Gérôme. It is also known as Young Greeks Attending a Cock Fight (Jeunes Grecs faisant battre des coqs). It is an example of the Neo-Grec style. It was one of Gérôme's first successes.",
  },
] satisfies NeoGrec

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default neoGrec
