// This file is automatically generated. Do not modify manually.

export type Neoplasticism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const neoplasticism: Neoplasticism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Piet_Mondriaan%2C_1930_-_Mondrian_Composition_II_in_Red%2C_Blue%2C_and_Yellow.jpg",
    paintingLabel: "Composition II in Red, Blue, and Yellow",
    artistName: "Piet Mondrian",
    date_of_birth: "1872",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/0b/Piet_Mondrian_2.jpg",
    movementLabel: "Neoplasticism",
    width: "46",
    height: "46",
    description: "painting by Piet Mondrian",
    abstract:
      "Composition with Red Blue and Yellow is a 1930 painting by Piet Mondrian. A well-known work of art, Mondrian contributes to the abstract visual language in a large way despite using a relatively small canvas. Thick, black brushwork defines the borders of the different geometric figures. Comparably, the black brushwork on the canvas is minimal but it is masterfully applied to become one of the defining features of the work.",
  },
] satisfies Neoplasticism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default neoplasticism
