// This file is automatically generated. Do not modify manually.

export type NovecentoItaliano = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const novecentoItaliano: NovecentoItaliano = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/29/Quarto_Stato.jpg",
    paintingLabel: "The Fourth Estate",
    artistName: "Giuseppe Pellizza da Volpedo",
    date_of_birth: "1868",
    date_of_death: "1907",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/41/Giuseppe_Pellizza.jpg",
    movementLabel: "Novecento Italiano",
    width: "550",
    height: "283",
    description: "picture painted by Giuseppe Pellizza da Volpedo in 1901",
    abstract:
      "The Fourth Estate is a famous picture painted by Giuseppe Pellizza da Volpedo between 1899 and 1901, originally entitled The Path of Workers.",
  },
] satisfies NovecentoItaliano

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default novecentoItaliano
