// This file is automatically generated. Do not modify manually.

export type Primitivism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const primitivism: Primitivism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/2f/Paul_Gauguin_-_I_Raro_te_Oviri_%281891%29.jpg",
    paintingLabel: "Under the Pandanus (I Raro te Oviri)",
    artistName: "Paul Gauguin",
    date_of_birth: "1848",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4f/Paul_Gauguin_111.jpg",
    movementLabel: "primitivism",
    width: "90",
    height: "68",
    description: "painting by Paul Gauguin",
  },
] satisfies Primitivism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default primitivism
