// This file is automatically generated. Do not modify manually.

export type ScientificRealism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const scientificRealism: ScientificRealism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/2/21/The_Agnew_Clinic_-_Thomas_Eakins.jpg",
    paintingLabel: "The Agnew Clinic",
    artistName: "Thomas Eakins",
    date_of_birth: "1844",
    date_of_death: "1916",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/7/7c/Eakins_selfportrait.jpg",
    movementLabel: "scientific realism",
    width: "300",
    height: "214",
    description: "painting by Thomas Eakins",
    abstract:
      "The Agnew Clinic (or The Clinic of Dr. Agnew) is an 1889 oil painting by American artist Thomas Eakins. It was commissioned to honor anatomist and surgeon David Hayes Agnew, on his retirement from teaching at the University of Pennsylvania.",
  },
] satisfies ScientificRealism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default scientificRealism
