// This file is automatically generated. Do not modify manually.

export type SocialistRealism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const socialistRealism: SocialistRealism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/8/89/Maxim_Gorky_by_Isaak_Brodsky_%281937%2C_GTG%29.jpeg",
    paintingLabel: "Maxim Gorky",
    artistName: "Isaak Brodsky",
    date_of_birth: "1883",
    date_of_death: "1939",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/9/93/Brodsky_by_Repin.jpg",
    movementLabel: "socialist realism",
    description: "painting by Isaak Brodski",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/73/The_Worker_and_Kolkhoz_Woman.jpg",
    paintingLabel: "Worker and Kolkhoz Woman",
    artistName: "Vera Ignatyevna Mukhina",
    date_of_birth: "1889",
    date_of_death: "1953",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/5/5e/1989_CPA_6077.jpg",
    movementLabel: "socialist realism",
    height: "24.5",
    description: "monumental sculpture",
    abstract:
      "Worker and Kolkhoz Woman (Russian: Рабо́чий и колхо́зница, tr. Rabóchy i kolkhóznitsa) is a sculpture of two figures with a sickle and a hammer raised over their heads. It is 24.5 meters (78 feet) high, made from stainless steel by Vera Mukhina for the 1937 World's Fair in Paris, and subsequently moved to Moscow. The sculpture is an example of socialist realism in an Art Deco aesthetic. The worker holds aloft a hammer and the kolkhoz woman a sickle to form the hammer and sickle symbol.\\n\\n",
  },
] satisfies SocialistRealism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default socialistRealism
