// This file is automatically generated. Do not modify manually.

export type Tonalism = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const tonalism: Tonalism = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a9/The_Canal_-_Albert_Pinkham_Ryder.jpg",
    paintingLabel: "The Canal",
    artistName: "Albert Pinkham Ryder",
    date_of_birth: "1847",
    date_of_death: "1917",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/39/Albert_Pinkham_Ryder.jpg",
    movementLabel: "Tonalism",
    description: "painting by Albert Pinkham Ryder",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0f/Moon_over_the_Forest_by_Charles_Warren_Eaton.jpg",
    paintingLabel: "Moon over the Forest",
    artistName: "Charles Warren Eaton",
    date_of_birth: "1857",
    date_of_death: "1937",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/0/05/Charles_Warren_Eaton.jpg",
    movementLabel: "Tonalism",
    description: "painting by Charles Warren Eaton",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/98/Sierra_Storm_by_William_Keith.jpg",
    paintingLabel: "Sierra Storm",
    artistName: "William Keith",
    date_of_birth: "1838",
    date_of_death: "1911",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/7/74/William_Ketih_Artist.jpg",
    movementLabel: "Tonalism",
    width: "21",
    height: "17.5",
    description: "painting by William Keith",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/6a/James_McNeill_Whistler_-_Nocturne_en_bleu_et_argent.jpg",
    paintingLabel: "Nocturne: Blue and Silver – Chelsea",
    artistName: "James Abbott McNeill Whistler",
    date_of_birth: "1834",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/e1/Whistler_Selbstportr%C3%A4t.jpg",
    movementLabel: "Tonalism",
    width: "50.2",
    height: "60.8",
    description: "painting by James Abbott McNeill Whistler",
    abstract:
      "Nocturne: Blue and Silver – Chelsea is a painting. It is the earliest of the London Nocturnes by James McNeill Whistler. It was conceived on the same August evening as Variations in Violet and Green. The two paintings were exhibited together at the Dudley Gallery.",
  },
] satisfies Tonalism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default tonalism
