// This file is automatically generated. Do not modify manually.

export type ViennaSecession = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const viennaSecession: ViennaSecession = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c5/Beethovenfries.jpg",
    paintingLabel: "The Hostile Powers, the Titan Typhoeus, the Three Gorgons",
    artistName: "Gustav Klimt",
    date_of_birth: "1862",
    date_of_death: "1918",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/d8/Klimt.jpg",
    movementLabel: "Vienna Secession",
    description: "painting by Gustav Klimt",
  },
  {
    image: "https://upload.wikimedia.org/wikipedia/commons/1/13/Pear_Tree.jpg",
    paintingLabel: "Pear Tree",
    artistName: "Gustav Klimt",
    date_of_birth: "1862",
    date_of_death: "1918",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/d8/Klimt.jpg",
    movementLabel: "Vienna Secession",
    width: "101",
    height: "101",
    description: "painting by Gustav Klimt",
    abstract:
      "Birnbaum (English : Pear tree) is a painting by Gustav Klimt from his Golden phase. This painting was painted in 1903, and today is housed in Busch-Reisinger Museum, Harvard University Art Museums, United States. Klimt finished this painting during his stay in Litzlberg on Lake Attersee.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0e/Klimt_-_Bethovenfries_-_Mittelwand.jpeg",
    paintingLabel: "Beethoven Frieze",
    artistName: "Gustav Klimt",
    date_of_birth: "1862",
    date_of_death: "1918",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/d8/Klimt.jpg",
    movementLabel: "Vienna Secession",
    description:
      "mural painting by Gustav Klimt painted on three walls of a room",
    abstract:
      "The Beethoven Frieze is a painting by Gustav Klimt on display in the Secession Building, Vienna, Austria.",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/31/Gustav_Klimt_044.jpg",
    paintingLabel: "Nuda Veritas",
    artistName: "Gustav Klimt",
    date_of_birth: "1862",
    date_of_death: "1918",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/d8/Klimt.jpg",
    movementLabel: "Vienna Secession",
    width: "55.2",
    height: "252",
    description: "painting by Gustav Klimt",
  },
] satisfies ViennaSecession

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default viennaSecession
