// This file is automatically generated. Do not modify manually.

export type VisualArtOfTheUnitedStates = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const visualArtOfTheUnitedStates: VisualArtOfTheUnitedStates = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/James_Abbot_McNeill_Whistler_007.jpg",
    paintingLabel: "Harmony in blue and silver: Trouville",
    artistName: "James Abbott McNeill Whistler",
    date_of_birth: "1834",
    date_of_death: "1903",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/e1/Whistler_Selbstportr%C3%A4t.jpg",
    movementLabel: "Visual art of the United States",
    width: "76",
    height: "50",
    description: "painting by James Abbott McNeill Whistler",
  },
] satisfies VisualArtOfTheUnitedStates

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default visualArtOfTheUnitedStates
