// This file is automatically generated. Do not modify manually.

export type YGa = {
  image: string
  paintingLabel: string
  artistName: string
  date_of_birth?: string | undefined
  date_of_death?: string | undefined
  image_of_artist?: string | undefined
  movementLabel: string
  width?: string | undefined
  height?: string | undefined
  creationYear?: string | undefined
  description?: string | undefined
  abstract?: string | undefined
}[]

const yGa: YGa = [
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/d/d5/Asai_Chu_-_Washing_Place_in_Grez-sur-Loing_-_Google_Art_Project.jpg",
    paintingLabel: "Washing Place in Grez-sur-Loing",
    artistName: "Asai Chū",
    date_of_birth: "1856",
    date_of_death: "1907",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Asai_chu.jpg",
    movementLabel: "Yōga",
    width: "455",
    height: "333",
    description: "painting by Asai Chū",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/75/Kuroda_Maiko.jpg",
    paintingLabel: "Maiko",
    artistName: "Kuroda Seiki",
    date_of_birth: "1866",
    date_of_death: "1924",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/c/cb/Kuroda_Seiki.jpg",
    movementLabel: "Yōga",
    width: "65.3",
    height: "80.4",
    description: "painting by Kuroda Seiki",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/73/Asai_Chu_-_Bridge_in_Grez-sur-Loing_-_Google_Art_Project.jpg",
    paintingLabel: "Bridge in Grez-sur-Loing",
    artistName: "Asai Chū",
    date_of_birth: "1856",
    date_of_death: "1907",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Asai_chu.jpg",
    movementLabel: "Yōga",
    width: "435",
    height: "284",
    description: "painting by Asai Chū",
  },
  {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/36/Asai_Chu_-_Woman_Sewing_-_Google_Art_Project.jpg",
    paintingLabel: "Woman Sewing",
    artistName: "Asai Chū",
    date_of_birth: "1856",
    date_of_death: "1907",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/3/33/Asai_chu.jpg",
    movementLabel: "Yōga",
    width: "455",
    height: "607",
    description: "painting by Asai Chū",
  },
] satisfies YGa

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default yGa
