// This file is automatically generated. Do not modify manually.

export type Ahgohebhbilyngcklepl = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const ahgohebhbilyngcklepl: Ahgohebhbilyngcklepl = {
  id: "ahgohebhbilyngcklepl",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/3a/Monet_Luncheon.jpg",
    paintingLabel: "The Luncheon",
    artistName: "Claude Monet",
    date_of_birth: "1840",
    date_of_death: "1926",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg",
    movementLabel: "Impressionism",
    width: "201",
    height: "160",
    description: "painting by Claude Monet (musée d'Orsay)",
    depicts: [
      "brooch",
      "dress",
      "mug",
      "salt and pepper shakers",
      "tea",
      "lunch",
      "plate",
      "teacup",
      "spoon",
      "bread",
      "tablecloth",
      "boy",
      "woman",
      "book",
      "lamp",
      "newspaper",
      "oils",
      "vinegar",
      "egg cup",
      "biscuit",
      "fork",
      "chair",
      "shell bowl",
      "window",
      "dinner",
      "cup",
      "egg",
      "Étretat",
      "wine",
      "knife",
      "bottle",
      "domestic worker",
      "door",
      "grape",
      "table",
      "hat",
      "child",
      "garden",
      "house",
      "avenue",
      "flower",
      "tree",
      "fruit",
      "construction set",
      "game",
      "Fuchsia",
      "landscape",
      "desserte (French)",
      "tableware",
      "Geranium",
      "Geraniaceae",
      "compote bowl",
      "Jean Monet",
      "coffeepot",
      "saucer",
      "daylight",
      "strolling",
      "bag",
      "umbrella",
      "Argenteuil",
      "parasol",
      "straw hat",
      "shadow",
      "tray",
      "ribbon",
      "bench",
      "broad-leaved tree",
      "sitting",
    ],
  },
  prompt:
    "Painting in the style of Claude Monet. </p>\n<p>Here is a prompt that you can use:</p>\n<p>Generate a painting of a domestic scene, inspired by Claude Monet's Impressionist style, depicting a woman and a boy sitting at a table, surrounded by various household items such as a brooch dress, mug, salt and pepper shakers, tea, lunch plate, teacup, spoon, bread, tablecloth, book, lamp, newspaper, oils, vinegar, egg cup, biscuit fork, chair, shell, bowl, window, dinner cup, egg, Étretat wine,",
  result: 1,
} satisfies Ahgohebhbilyngcklepl

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ahgohebhbilyngcklepl
