// This file is automatically generated. Do not modify manually.

export type Fnclerpjdgekkpmmqdwj = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: string | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const fnclerpjdgekkpmmqdwj: Fnclerpjdgekkpmmqdwj = {
  id: "fnclerpjdgekkpmmqdwj",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/06/Edouard_Manet_-_On_the_Beach_-_Google_Art_Project.jpg",
    paintingLabel: "Sur la plage",
    artistName: "Édouard Manet",
    date_of_birth: "1832",
    date_of_death: "1883",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/2/20/%C3%89douard_Manet%2C_en_buste%2C_de_face_-_Nadar.jpg",
    movementLabel: "Impressionism",
    width: "735",
    height: "600",
    description: "painting by Édouard Manet",
    depicts: [
      "woman",
      "beach",
      "parasol",
      "child",
      "sea",
      "dress",
      "sailing ship",
      "Berck",
      "entertainment",
      "profil perdu",
      "foam",
      "English Channel",
      "half reclining",
      "beret",
      "coif",
      "wind wave",
      "reading",
      "brown hair",
      "sailboat",
      "beard",
      "sitting",
      "sky",
      "man",
    ],
  },
  prompt: "a cool cat",
  result: 0,
} satisfies Fnclerpjdgekkpmmqdwj

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default fnclerpjdgekkpmmqdwj
