// This file is automatically generated. Do not modify manually.

export type Lhlnnbmpptynwwkgulvy = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: string | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const lhlnnbmpptynwwkgulvy: Lhlnnbmpptynwwkgulvy = {
  id: "lhlnnbmpptynwwkgulvy",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/6/63/Nicolae_Grigorescu_-_Portretul_Zettinei_Urechia.jpg",
    paintingLabel: "Portrait of Zettine Urechia",
    artistName: "Nicolae Grigorescu",
    date_of_birth: "1838",
    date_of_death: "1907",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/bd/Nicolae_Grigorescu_-_Foto02.jpg",
    movementLabel: "Impressionism",
    width: "52",
    height: "63",
    description: "painting by Nicolae Grigorescu",
    depicts: [],
  },
  prompt:
    "Painting in the style of Nicolae Grigorescu.  \n\nA young woman with a serene expression sits in a chair, her hands folded in her lap, wearing a blue dress with a white collar and a golden brooch at her neck, against a warm beige background",
  result: 1,
} satisfies Lhlnnbmpptynwwkgulvy

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default lhlnnbmpptynwwkgulvy
