// This file is automatically generated. Do not modify manually.

export type Nymtruukpifxmcbfuakg = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: string | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const nymtruukpifxmcbfuakg: Nymtruukpifxmcbfuakg = {
  id: "nymtruukpifxmcbfuakg",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/5a/Nicolae_Grigorescu_-_Taranca_citind.jpg",
    paintingLabel: "Peasant reading,",
    artistName: "Nicolae Grigorescu",
    date_of_birth: "1838",
    date_of_death: "1907",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/b/bd/Nicolae_Grigorescu_-_Foto02.jpg",
    movementLabel: "Impressionism",
    width: "19",
    height: "27",
    description: "painting by Nicolae Grigorescu",
    depicts: [],
  },
  prompt:
    "Painting in the style of Nicolae Grigorescu.  A peasant is shown sitting in a rustic setting, reading a book with a look of quiet contemplation on his face",
  result: 1,
} satisfies Nymtruukpifxmcbfuakg

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default nymtruukpifxmcbfuakg
