// This file is automatically generated. Do not modify manually.

export type Osxqvtgoteuguklojkdk = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const osxqvtgoteuguklojkdk: Osxqvtgoteuguklojkdk = {
  id: "osxqvtgoteuguklojkdk",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b8/Firma_de_Guillermo_Silveira_1984.jpg",
    paintingLabel: "Men and machines",
    artistName: "Guillermo Silveira García",
    date_of_birth: "1922",
    date_of_death: "1987",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/5/5e/Retrato_de_Guillermo_Silveira.jpg",
    movementLabel: "expressionism",
    width: "89",
    height: "160",
    description: "painting by Guillermo Silveira García",
    depicts: [],
  },
  prompt:
    "a close up of a skateboard with graffiti on it, an ultrafine detailed painting by André Castro, reddit contest winner, stuckism, artwork, detailed painting, high detail, hyperrealistic, photorealistic, photo realistic, digital art, digital painting, 8k, 4k, 8 k, 4 k, 8k resolution, 4k resolution, 8k uhd, 4k uhd, ultra hd, ultra high definition, ultra high resolution",
  result: 0,
} satisfies Osxqvtgoteuguklojkdk

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default osxqvtgoteuguklojkdk
