// This file is automatically generated. Do not modify manually.

export type Qoglsxjhxrvfvvszbjoe = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const qoglsxjhxrvfvvszbjoe: Qoglsxjhxrvfvvszbjoe = {
  id: "qoglsxjhxrvfvvszbjoe",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0f/Munch_Moonlight.jpg",
    paintingLabel: "Moonlight",
    artistName: "Edvard Munch",
    date_of_birth: "1863",
    date_of_death: "1944",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/4/4a/Edvard_Munch_1933-2.jpg",
    movementLabel: "expressionism",
    width: "110",
    height: "93",
    description: "painting by Edvard Munch (1895)",
    depicts: [
      "tree",
      "boat",
      "body of water",
      "moonlight",
      "Moon",
      "house",
      "mountain",
      "light source",
      "landscape",
      "plain",
      "horizon",
      "sky",
      "contre-jour",
      "night",
      "Pelto",
      "summer",
      "fence",
      "woman",
      "beach",
      "Norway",
      "Oslofjord",
      "trunk",
      "specular reflection",
      "grass",
      "shore",
    ],
  },
  prompt:
    "a painting of a full moon over a body of water, an ultrafine detailed painting by Edvard Munch, deviantart, synthetism, impressionism, fauvism, soft light, two people walking on a beach",
  result: 0,
} satisfies Qoglsxjhxrvfvvszbjoe

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default qoglsxjhxrvfvvszbjoe
