// This file is automatically generated. Do not modify manually.

export type Qrwhosbsrrhnwkqrwwwo = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const qrwhosbsrrhnwkqrwwwo: Qrwhosbsrrhnwkqrwwwo = {
  id: "qrwhosbsrrhnwkqrwwwo",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/95/Claude_Monet_024.jpg",
    paintingLabel: "Women in the Garden",
    artistName: "Claude Monet",
    date_of_birth: "1840",
    date_of_death: "1926",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg",
    movementLabel: "Impressionism",
    width: "205",
    height: "255",
    description: "painting by Claude Monet, 1866",
    abstract:
      "Women in the Garden (French: Femmes au jardin) is an oil painting begun in 1866 by French artist Claude Monet when he was 26. It is a large work painted en plein air; the size of the canvas necessitated Monet painting its upper half with the canvas lowered into a trench he had dug, so that he could maintain a single point of view for the entire work. The setting is the garden of a property he was renting. His companion Camille posed for the figures. Monet finished the work indoors, and used magazine illustrations to render fashionable clothing.\\nMonet at this time was early in his career, experimenting with method and subject matter. His earlier paintings were successful at Paris Salons, but Women in the Garden was rejected in 1867 on the grounds of subject and narrative weakness. The Salon was also troubled by Monet's heavy brushstrokes, a style which would, of course, become one of the hallmarks of Impressionism. A judge commented, 'Too many young people think of nothing but continuing in this abominable direction. It is high time to protect them and save art!'  The painting was purchased by fellow artist Frédéric Bazille to help support Monet at a time when he had no money.Although the Musée d'Orsay, the painting's owner, comments that 'Monet has skilfully rendered the white of the dresses, anchoring them firmly in the structure of the composition', Christoph Heinrich, author of a Monet biography, notes how posterity has found the painting lacking. In this view, the figures appear poorly integrated into the scene, with the woman at right 'gliding across the ground as if she had a trolley concealed beneath her dress'. The painting's treatment of light and shadow is lauded, however, and in this respect the work may have shown Monet where his artistic path lay.",
    depicts: [
      "garden",
      "flower",
      "tree",
      "dress",
      "landscape",
      "clothing",
      "Ville-d'Avray",
      "stripe",
      "Camille Doncieux",
      "umbrella",
      "sitting",
      "woman",
    ],
  },
  prompt:
    "a painting of a group of women in dresses, an impressionist painting by Blanche Hoschedé Monet, trending on pinterest, impressionism, impressionism, pre-raphaelite, creative commons attribution, women in the garden, claude monet, ville-d'avray, camille doncieux, umbrella, sitting woman, stripe, tree, flower, landscape, clothing",
  result: 0,
} satisfies Qrwhosbsrrhnwkqrwwwo

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default qrwhosbsrrhnwkqrwwwo
