// This file is automatically generated. Do not modify manually.

export type Tloosgusbelpbtawlbjq = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: string | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const tloosgusbelpbtawlbjq: Tloosgusbelpbtawlbjq = {
  id: "tloosgusbelpbtawlbjq",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/90/Steer_Ethel.jpg",
    paintingLabel: "Portrait of Miss Ethel Warwick",
    artistName: "Philip Wilson Steer",
    date_of_birth: "1860",
    date_of_death: "1942",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/aa/Philip_Wilson_Steer_photo_by_George_Charles_Beresford_1922_%281%29.jpg",
    movementLabel: "Impressionism",
    description: "painting by Philip Wilson Steer",
    depicts: ["dress", "Ethel Warwick", "choker", "ribbon", "sitting", "woman"],
  },
  prompt:
    "Painting in the style of Philip Wilson Steer.  A young woman with a gentle face and a soft, golden glow surrounding her, sits in a relaxed pose, her hands folded in her lap and her eyes cast downward, amidst a background of subtle, muted colors",
  result: 0,
} satisfies Tloosgusbelpbtawlbjq

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default tloosgusbelpbtawlbjq
