// This file is automatically generated. Do not modify manually.

export type Wrtjvrhntrlvlqfbvcod = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const wrtjvrhntrlvlqfbvcod: Wrtjvrhntrlvlqfbvcod = {
  id: "wrtjvrhntrlvlqfbvcod",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Claude_Monet_-_Woman_with_a_Parasol_-_Madame_Monet_and_Her_Son_-_Google_Art_Project.jpg",
    paintingLabel: "La Promenade",
    artistName: "Claude Monet",
    date_of_birth: "1840",
    date_of_death: "1926",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg",
    movementLabel: "Impressionism",
    width: "82",
    height: "100",
    description: "painting by Claude Monet, 1875 foot",
    abstract:
      "Woman with a Parasol - Madame Monet and Her Son, sometimes known as The Stroll (French: La Promenade) is an oil-on-canvas painting by Claude Monet from 1875. The Impressionist work depicts his wife Camille Monet and their son Jean Monet in the period from 1871 to 1877 while they were living in Argenteuil, capturing a moment on a stroll on a windy summer's day.",
    depicts: [
      "stream",
      "plant",
      "dress",
      "middle class",
      "leaf",
      "shoe",
      "strolling",
      "straw hat",
      "vest",
      "jacket",
      "trousers",
      "earring",
      "moustache",
      "grass",
      "couple",
      "black hair",
      "eyebrow",
      "chignon",
      "shore",
      "blond",
      "hat",
      "man",
      "woman",
      "meadow",
      "Jean Monet",
      "rural area",
      "Camille Doncieux",
      "daylight",
      "son",
      "Argenteuil",
      "parasol",
      "shadow",
      "contre-jour",
      "ribbon",
      "coif",
      "standing",
      "mother",
      "child",
      "boy",
      "cloud",
      "sky",
    ],
  },
  prompt:
    "a painting of a woman holding a green umbrella, an impressionist painting by Blanche Hoschedé Monet, pixabay contest winner, impressionism, impressionism, painterly, oil on canvas, wearing a yellow dress, with a blue ribbon in her hair",
  result: 1,
} satisfies Wrtjvrhntrlvlqfbvcod

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default wrtjvrhntrlvlqfbvcod
