// This file is automatically generated. Do not modify manually.

export type Ceoiczlkhazougobjjev = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const ceoiczlkhazougobjjev: Ceoiczlkhazougobjjev = {
  id: "ceoiczlkhazougobjjev",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/Calleja_de_T%C3%A1nger_by_Julio_Romero_de_Torres.JPG",
    paintingLabel: "Alley of Tangier",
    artistName: "Julio Romero de Torres",
    movementLabel: "Art Nouveau",
    date_of_birth: "1874",
    date_of_death: "1930",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/2/28/Julio_Romero_de_Torres.jpg",
    width: "12.5",
    height: "22",
    inception: "1903",
    description: "painting by Julio Romero de Torres",
    motifs: ["street"],
    genres: ["landscape art"],
    materials: ["oil paint", "panel"],
  },
  prompt:
    "a painting of a cat sitting in a doorway by Nicolas de Staël, pixiv, barbizon school, fresco, oil on canvas, egyptian art, impressionism, surrealism, cubism, abstract expressionism, pop art, minimalism, conceptual art, street art, graffiti, mural, installation, performance, video, photography, sculpture, architecture, design, fashion, advertising, graphic design, typography, calligraphy, illustration, animation, film, television, radio,",
  result: 1,
} satisfies Ceoiczlkhazougobjjev

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ceoiczlkhazougobjjev
