// This file is automatically generated. Do not modify manually.

export type Dpxfxcerqtifouimiflq = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const dpxfxcerqtifouimiflq: Dpxfxcerqtifouimiflq = {
  id: "dpxfxcerqtifouimiflq",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b8/Kirchner_1909_Marzella.jpg",
    paintingLabel: "Marzella",
    artistName: "Ernst Ludwig Kirchner",
    date_of_birth: "1880",
    date_of_death: "1938",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    movementLabel: "expressionism",
    width: "60",
    height: "76",
    description: "painting by Ernst Ludwig Kirchner",
    depicts: [
      "Lina Franziska Fehrmann",
      "mascara",
      "prostitute",
      "lipstick",
      "high-angle shot",
      "eyebrow",
      "bed",
      "gaze towards the viewer",
      "brown hair",
      "long hair",
      "girl",
      "nudity",
      "child",
      "sitting",
    ],
  },
  prompt:
    "a painting of a woman sitting on a couch, a cubist painting by Ernst Ludwig Kirchner, trending on pinterest, fauvism, fauvism, picasso, cubism, Marzella, Lina Franziska Fehrmann, mascara, prostitute, lipstick, high-angle shot, eyebrow, bed, gaze towards the viewer, brown hair, long hair, girl, nudity, child, sitting",
  result: 0,
} satisfies Dpxfxcerqtifouimiflq

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default dpxfxcerqtifouimiflq
