// This file is automatically generated. Do not modify manually.

export type Dseudiqmlvmtlxixffbt = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const dseudiqmlvmtlxixffbt: Dseudiqmlvmtlxixffbt = {
  id: "dseudiqmlvmtlxixffbt",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/a6/Claude_Monet_-_Waterloo-Br%C3%BCcke_-_1903.jpeg",
    paintingLabel: "Waterloo Bridge",
    artistName: "Claude Monet",
    movementLabel: "Impressionism",
    date_of_birth: "1840",
    date_of_death: "1926",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Claude_Monet_1899_Nadar_crop.jpg",
    width: "101",
    height: "65.3",
    inception: "1903",
    description: "painting by Claude Monet, 1903",
    motifs: ["Waterloo Bridge"],
    genres: ["cityscape"],
    materials: ["oil paint", "canvas"],
  },
  prompt:
    "a painting of a foggy sky with boats in the water, an impressionist painting by Blanche Hoschedé Monet, pixiv, impressionism, impressionism, mist, made of mist, oil paint, canvas, 65.3cm, 101cm",
  result: 0,
} satisfies Dseudiqmlvmtlxixffbt

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default dseudiqmlvmtlxixffbt
