// This file is automatically generated. Do not modify manually.

export type Gysfplmeoocshznbyyil = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const gysfplmeoocshznbyyil: Gysfplmeoocshznbyyil = {
  id: "gysfplmeoocshznbyyil",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/e/e7/Prince_Ferdinand_Philippe%2C_Duke_of_Orl%C3%A9ans_by_Ingres%2C_1832.jpg",
    paintingLabel: "Ferdinand-Philippe d'Orleans by Ingres - RF 2005-13",
    artistName: "Jean Auguste Dominique Ingres",
    movementLabel: "neoclassicism",
    date_of_birth: "1780",
    date_of_death: "1867",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Ingres%2C_Self-portrait.jpg",
    width: "122",
    height: "158",
    inception: "1832",
    country: "France",
    description: "painting by Jean-Auguste-Dominique Ingres",
    motifs: ["Prince Ferdinand Philippe, Duke of Orléans", "man"],
    genres: ["portrait"],
    materials: ["oil paint", "canvas"],
  },
  prompt:
    "a painting of a man in a military uniform, a character portrait by Eugène Delacroix, reddit contest winner, art informel, studio portrait, detailed painting, calotype, fine art, masterful brushwork, high quality, trending on ArtStation",
  result: 1,
} satisfies Gysfplmeoocshznbyyil

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default gysfplmeoocshznbyyil
