// This file is automatically generated. Do not modify manually.

export type Ighlvldkmwxgtnmnnvxd = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const ighlvldkmwxgtnmnnvxd: Ighlvldkmwxgtnmnnvxd = {
  id: "ighlvldkmwxgtnmnnvxd",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/7a/C_W_Eckersberg_1841_-_Kvinde_foran_et_spejl.jpg",
    paintingLabel: "A nude woman doing her hair before a mirror",
    artistName: "Christoffer Wilhelm Eckersberg",
    movementLabel: "neoclassicism",
    date_of_birth: "1783",
    date_of_death: "1853",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/Self_portrait%2C_by_Christoffer_Wilhelm_Eckersberg.jpg",
    width: "26",
    height: "33.5",
    inception: "1841",
    country: "Denmark",
    description: "painting by Christoffer Wilhelm Eckersberg",
    abstract:
      "A Nude Woman Doing Her Hair Before a Mirror (often only Woman in Front of a Mirror or with the old title A nude seen from the back, woman doing her hair before a mirror) is an oil painting from 1841 by the Danish Golden Age painter CW Eckersberg. The painting is in the Hirschsprung Collection in Copenhagen. The relatively small image is regarded as one of the Danish Golden Age masterpieces.",
    motifs: [
      "mirror",
      "hair care",
      "mirror image",
      "specular reflection",
      "intergluteal cleft",
      "earring",
      "back",
      "toplessness",
      "chignon",
      "brown hair",
      "woman",
    ],
    genres: ["nude", "genre art"],
    materials: ["oil paint", "canvas"],
  },
  prompt:
    "a painting of a woman brushing her hair in front of a mirror, an ultrafine detailed painting by Christoffer Wilhelm Eckersberg, featured on flickr, neoclassicism, dutch golden age, detailed painting, pre-raphaelite, painted in 1841, Denmark, 33.5cm, 26cm",
  result: 0,
} satisfies Ighlvldkmwxgtnmnnvxd

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ighlvldkmwxgtnmnnvxd
