// This file is automatically generated. Do not modify manually.

export type Ldcsdylorsoygeqlcwhe = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const ldcsdylorsoygeqlcwhe: Ldcsdylorsoygeqlcwhe = {
  id: "ldcsdylorsoygeqlcwhe",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Ernst-Ludwig-Kirchner-Weiblicher-Akt-mit-Hut-Museum-Ludwig.jpg",
    paintingLabel: "Half-Length Nude with Hat",
    artistName: "Ernst Ludwig Kirchner",
    movementLabel: "expressionism",
    date_of_birth: "1880",
    date_of_death: "1938",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    inception: "1911",
    description: "painting by Ernst Ludwig Kirchner",
    motifs: [
      "dress",
      "Doris Groß",
      "areola",
      "toplessness",
      "breast",
      "hat",
      "woman",
    ],
    genres: ["female nude", "nude"],
    materials: ["oil paint", "canvas"],
  },
  prompt:
    "a painting of a woman with a hat on her head, an art deco painting by Ernst Ludwig Kirchner, pixiv, expressionism, fauvism, 1920s, studio portrait, dress, Doris Groß, areola, toplessness, breast, hat, woman",
  result: 0,
} satisfies Ldcsdylorsoygeqlcwhe

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default ldcsdylorsoygeqlcwhe
