// This file is automatically generated. Do not modify manually.

export type Omutqtzykftdvklkxqxn = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const omutqtzykftdvklkxqxn: Omutqtzykftdvklkxqxn = {
  id: "omutqtzykftdvklkxqxn",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/3/36/Interior_d%27una_trattoria.jpg",
    paintingLabel: "Inside a trattoria",
    artistName: "Francesc Soler i Rovirosa",
    movementLabel: "Art Nouveau",
    date_of_birth: "1836",
    date_of_death: "1900",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/0/09/Francesc_Soler_i_Rovirosa.jpg",
    width: "225",
    height: "16",
    inception: "1895",
    description: "artwork by Francesc Soler i Rovirosa",
    motifs: ["Trattoria"],
    genres: ["interior"],
    materials: ["watercolor paint", "paper"],
  },
  prompt:
    "a drawing of a living room with a lot of furniture, a watercolor painting by James Gurney, pixiv contest winner, arts and crafts movement, matte drawing, concept art, official art, inside a trattoria",
  result: 0,
} satisfies Omutqtzykftdvklkxqxn

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default omutqtzykftdvklkxqxn
