// This file is automatically generated. Do not modify manually.

export type Qglfbwvpwognpxhgqvpb = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const qglfbwvpwognpxhgqvpb: Qglfbwvpwognpxhgqvpb = {
  id: "qglfbwvpwognpxhgqvpb",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/a/af/Franz_Marc_-_Akt_mit_Katze_-_G_12762_-_Lenbachhaus.jpg",
    paintingLabel: "nude with Cat",
    artistName: "Franz Marc",
    movementLabel: "expressionism",
    date_of_birth: "1880",
    date_of_death: "1916",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/FranzMarccropped.jpg",
    width: "82",
    height: "88",
    inception: "1910",
    description: "Franz Marc painting",
    motifs: ["house cat", "woman"],
    genres: ["nude"],
    materials: ["color", "canvas"],
  },
  prompt:
    "a painting of a man kneeling down on a bed by André Lhote, reddit contest winner, fauvism, fauvism, oil on canvas, chiaroscuro, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909, 1909,",
  result: 1,
} satisfies Qglfbwvpwognpxhgqvpb

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default qglfbwvpwognpxhgqvpb
