// This file is automatically generated. Do not modify manually.

export type Rprdmdscgqdeyhzwbrqk = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const rprdmdscgqdeyhzwbrqk: Rprdmdscgqdeyhzwbrqk = {
  id: "rprdmdscgqdeyhzwbrqk",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/Girl_in_the_shirt_%28Red-haired_girl%29_by_Amedeo_Modigliani.jpg",
    paintingLabel: "Girl in the shirt (Red-haired girl)",
    artistName: "Amedeo Modigliani",
    movementLabel: "expressionism",
    date_of_birth: "1884",
    date_of_death: "1920",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/0/07/Amedeo-modigliani-identification-photo-nice-1918.jpg",
    width: "50",
    height: "73",
    inception: "1918",
    description: "painting by Amedeo Modigliani",
    motifs: ["chemise", "blue", "red hair", "White people", "breast", "woman"],
    genres: ["nude", "portrait"],
    materials: ["oil paint", "canvas"],
  },
  prompt:
    "a painting of a woman in a white top by Amedeo Modigliani, pixiv, vorticism, picasso, academic art, studio portrait, chemise, blue, red hair, White people, breast, woman",
  result: 0,
} satisfies Rprdmdscgqdeyhzwbrqk

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default rprdmdscgqdeyhzwbrqk
