// This file is automatically generated. Do not modify manually.

export type Xtjqqhjsusmwtpodhplk = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const xtjqqhjsusmwtpodhplk: Xtjqqhjsusmwtpodhplk = {
  id: "xtjqqhjsusmwtpodhplk",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/0/0e/Paisatge_nocturn_amb_dues_noies_-_Joan_Brull_i_Vinyoles_%281863-1912%29.jpg",
    paintingLabel: "Nightscape with Two Girls",
    artistName: "Joan Brull Vinyoles",
    date_of_birth: "1863",
    date_of_death: "1912",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/d/d2/Autoretrat_-_Joan_Brull_i_Vinyoles_%281863-1912%29.jpg",
    movementLabel: "Art Nouveau",
    width: "80",
    height: "63",
    description: "painting by Joan Brull",
    depicts: ["tree", "dress", "Moon", "girl", "woman"],
  },
  prompt:
    'Painting in the style of Joan Brull Vinyoles. "\n\nThe prompt is written as follows:\n\n"Create a painting in the style of Joan Brull Vinyoles, an Art Nouveau artist from the early 20th century',
  result: 1,
} satisfies Xtjqqhjsusmwtpodhplk

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default xtjqqhjsusmwtpodhplk
