// This file is automatically generated. Do not modify manually.

export type Xyhfljgurauxjimwetko = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    image_of_artist?: string | undefined
    movementLabel: string
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    depicts?: (string | string[]) | undefined
    country?: string | undefined
  }
  prompt: string
  result: number
}

const xyhfljgurauxjimwetko: Xyhfljgurauxjimwetko = {
  id: "xyhfljgurauxjimwetko",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/c/c4/Joan_Roig_Soler-_Carrer-_1684.JPG",
    paintingLabel: "Street",
    artistName: "Joan Roig Soler",
    date_of_birth: "1852",
    date_of_death: "1909",
    image_of_artist:
      "https://upload.wikimedia.org/wikipedia/commons/e/eb/Joan_Roig_Soler-_Carrer_de_l%27esgl%C3%A9sia.JPG",
    movementLabel: "Art Nouveau",
    width: "165",
    height: "255",
    description: "painting by Joan Roig i Soler",
    depicts: ["street"],
  },
  prompt:
    'Painting in the style of Joan Roig Soler. "\n\nThe prompt should include the following elements:\n\n1',
  result: 1,
} satisfies Xyhfljgurauxjimwetko

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default xyhfljgurauxjimwetko
