// This file is automatically generated. Do not modify manually.

export type Zwoxtbqeoqujcurbrbvl = {
  id: string
  artwork: {
    image: string
    paintingLabel: string
    artistName: string
    movementLabel: string
    date_of_birth?: string | undefined
    date_of_death?: string | undefined
    artist_img?: string | undefined
    width?: string | undefined
    height?: string | undefined
    inception?: string | undefined
    country?: string | undefined
    description?: string | undefined
    abstract?: string | undefined
    motifs: string[]
    genres: string[]
    materials: string[]
  }
  prompt: string
  result: number
}

const zwoxtbqeoqujcurbrbvl: Zwoxtbqeoqujcurbrbvl = {
  id: "zwoxtbqeoqujcurbrbvl",
  artwork: {
    image:
      "https://upload.wikimedia.org/wikipedia/commons/b/b8/Kirchner_1909_Marzella.jpg",
    paintingLabel: "Marzella",
    artistName: "Ernst Ludwig Kirchner",
    movementLabel: "expressionism",
    date_of_birth: "1880",
    date_of_death: "1938",
    artist_img:
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Kirchner_1919_portrait.jpg",
    width: "60",
    height: "76",
    inception: "1909",
    description: "painting by Ernst Ludwig Kirchner",
    motifs: [
      "Lina Franziska Fehrmann",
      "mascara",
      "prostitute",
      "lipstick",
      "high-angle shot",
      "eyebrow",
      "bed",
      "gaze towards the viewer",
      "brown hair",
      "long hair",
      "girl",
      "nudity",
      "child",
      "sitting",
    ],
    genres: ["nude", "portrait"],
    materials: ["oil paint", "canvas"],
  },
  prompt:
    "a painting of a woman sitting on a couch, a cubist painting by Ernst Ludwig Kirchner, trending on pinterest, fauvism, fauvism, picasso, cubism, Lina Franziska Fehrmann, mascara, prostitute, lipstick, high-angle shot, eyebrow, bed, gaze towards the viewer, brown hair, long hair, girl, nudity, child, sitting",
  result: 0,
} satisfies Zwoxtbqeoqujcurbrbvl

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default zwoxtbqeoqujcurbrbvl
