// This file is automatically generated. Do not modify manually.

export type Expressionism = {
  id: string
  name: string
  questions: string[]
}

const expressionism: Expressionism = {
  id: "expressionism",
  name: "expressionism",
  questions: [
    "qoglsxjhxrvfvvszbjoe",
    "xnwnafnpaleegeiuqtcl",
    "osxqvtgoteuguklojkdk",
    "dpxfxcerqtifouimiflq",
    "jyqijyscmeoxoritxdyv",
  ],
} satisfies Expressionism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default expressionism
