// This file is automatically generated. Do not modify manually.

export type Impressionism = {
  id: string
  name: string
  questions: string[]
}

const impressionism: Impressionism = {
  id: "impressionism",
  name: "Impressionism",
  questions: [
    "tpbkzxikcboyfvwfylwi",
    "hcgjpyhtjaseuhwqphlz",
    "ibpqkyxvjurdxnklddsw",
    "jlmplrldbhibfqwdyrog",
    "dseudiqmlvmtlxixffbt",
    "teljehrhnxfrmridwthn",
    "oseknjdaoaycmezcietj",
    "heehhjopnubslgdijqpk",
    "hwlvhtnseefjmrwsotsz",
    "bcxfdafmapxgmwyfkqik",
  ],
} satisfies Impressionism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default impressionism
