// This file is automatically generated. Do not modify manually.

export type Neoclassicism = {
  id: string
  name: string
  questions: string[]
}

const neoclassicism: Neoclassicism = {
  id: "neoclassicism",
  name: "neoclassicism",
  questions: [
    "cmotxgqyivknjsordzty",
    "vlrnabswgihxvvpbllpi",
    "efnrmkksstinkqcjkuuq",
    "ndhumugknvaqhrewpmvj",
    "vdchzmbekpibpjxaaoix",
    "gysfplmeoocshznbyyil",
    "ighlvldkmwxgtnmnnvxd",
    "lisyohnhtfhdfslvzpku",
    "rcywcqladkegcycgvdvk",
    "bjcanvhwlvgllxrglara",
  ],
} satisfies Neoclassicism

// Export as default value to avoid a weird bug where json files are sometimes preferred over ts files
export default neoclassicism
